const akronoh = [
    { artist: "Ralph Carney", spotifyID: "0pa2mkOjPCweXAyOK38OIl", popularity: 36 },
    { artist: "Tim Easton", spotifyID: "11ixEVNpyaaCW7VfC7fx8M", popularity: 18.0 },
    { artist: "Patrick Carney", spotifyID: "6yPEOdG1RrtchjBRdnu8tu", popularity: 40.0 },
    { artist: "Dan Auerbach", spotifyID: "6YWdHD3R863Apw1hkx3BwC", popularity: 60.0 },
    { artist: "Joseph Arthur", spotifyID: "5aD0uh1BpYTN7AzhiSDgaO", popularity: 40.0 },
    { artist: "Joe Glazer", spotifyID: "0mbpwhdmzWPMzw0881Ylzt", popularity: 20.0 },
    { artist: "Roger Hoover", spotifyID: "7tmcpzv3bbNPx3l46qT4Bm", popularity: 4.0 },
    { artist: "Phillip Ingram", spotifyID: "0avnJVsLYqeNt4yBNaicYC", popularity: 0.0 },
    { artist: "Chrissie Hynde", spotifyID: "2ozLlEZTdSV3pjHgWwZMsi", popularity: 51.0 },
    { artist: "Gary Garcia", spotifyID: "3yoY1qdJ2xLCDsfRPWUX0m", popularity: 0.0 },
    { artist: "James Ingram", spotifyID: "5bTTx0CRvZj1kRJwUsWWYo", popularity: 59.0 },
    { artist: "Dem Atlas", spotifyID: "2ttC18RelZhUEjhJhJXSbJ", popularity: 46.0 },
    { artist: "Howard Hewett", spotifyID: "3S78Gzhp1D01i1x2KGXrnh", popularity: 40.0 },
    { artist: "Mark Mothersbaugh", spotifyID: "5sEDTHJJyDEWVFx99hGSIb", popularity: 49.0 },
    { artist: "Queena Mario", spotifyID: "3XTmhxjAdQAJSFg9AUvVFP", popularity: 0.0 },
    { artist: "Patty Donahue", spotifyID: "2KBEzeNpH1bRgkQfL2GPz1", popularity: 16.0 },
    { artist: "Len Chandler", spotifyID: "641w67BH81V0VVhxM1Tkya", popularity: 10.0 },
    { artist: "Robert Quine", spotifyID: "3wlJVzgGuOjUgwVUnagWSt", popularity: 0.0 },
    { artist: "Grandpa Jones", spotifyID: "2UtCcZQl7xzvEao4vWBSOD", popularity: 31.0 },
    { artist: "Swoope", spotifyID: "78ZdtwvDD5zTElro6EGkcU", popularity: 47.0 },
    { artist: "Grant Clarke", spotifyID: "1ajrfhST6RmMQGLYm1vd6e", popularity: 0.0 },
    { artist: "Phil Kline", spotifyID: "6o1X48REXSi8q1H0PGAfOL", popularity: 3.0 },
    { artist: "Jeff Golub", spotifyID: "12455ZzxS49FbAGWKeB9eB", popularity: 39.0 },
    { artist: "Bob Lewis", spotifyID: "0A0EnkUYQEy3g8BlCujLDE", popularity: 0.0 },
    { artist: "Brad Warner", spotifyID: "7qe7dNDsQ4qZWgighrXjMw", popularity: 0.0 },
    { artist: "Jani Lane", spotifyID: "1wXLIfZqD0BULRJH0OX37F", popularity: 31.0 },
    { artist: "Ampichino", spotifyID: "04HECiWVE4ogBNdOvJuyps", popularity: 40.0 },
    { artist: "Helen Jepson", spotifyID: "7JmqEidlDp0pMgKYCLllWr", popularity: 1.0 },
    { artist: "Jimmy Work", spotifyID: "1WgILuwwQ3x8XHYb6fyna7", popularity: 3.0 },
    { artist: "Tim 'Ripper' Owens", spotifyID: "1kcDiFxJ4pv9tVARvStqTN", popularity: 25.0 },
    { artist: "Jim Jarmusch", spotifyID: "7uwCnAgRDUzftIAkJDFfdy", popularity: 22.0 },
    { artist: "Russell Oberlin", spotifyID: "3soTdlHsjyDZOr7D7TmjGn", popularity: 4.0 },
    { artist: "Rachel Sweet", spotifyID: "3E8iIu6yKztcuEHrKFBNMS", popularity: 28.0 },
    { artist: "Neal Smith", spotifyID: "6VolEVrbkf9vEpAuMJilDu", popularity: 7.0 },
    { artist: "Marian Mercer", spotifyID: "7nFYH4wVZa8mvBnyMJIcdQ", popularity: 0.0 },
    { artist: "Todd Tobias", spotifyID: "07TxSkT0uXqDoZTLH5Vwlg", popularity: 0.0 },
    { artist: "Nikola Resanovic", spotifyID: "2Tm286U0o6Mkum7RBI2LRE", popularity: 0.0 },
    { artist: "Jim Wise", spotifyID: "6yVfd2ifZnRceajsWyWuFx", popularity: 19.0 },
    { artist: "Bob Neuwirth", spotifyID: "1h3QYheSnWDO2cIVew48bB", popularity: 24.0 },
    { artist: "Vaughn Monroe", spotifyID: "5TD3Mad384osX9K8DLkx7L", popularity: 32.0 },
]

module.exports = akronoh;