[{ artist: "Christopher Bolduc", spotifyID: "0d9OXZ3YNc8Xi3t41jT8bW", popularity: 0.0 },
{ artist: "Jason Bittner", spotifyID: "3gFahi4Jiwvmr6UCG9Sz6J", popularity: 0.0 },
{ artist: "Drug Church", spotifyID: "6q4AmzK3GzCuEzkurnYuEQ", popularity: 42.0 },
{ artist: "David Alan Miller", spotifyID: "7jsY4twYEKz5V2awNkoEax", popularity: 13.0 },
{ artist: "Sev Statik", spotifyID: "0E1wxJCj4idZpFyNZAeIOh", popularity: 5.0 },
{ artist: "Nikki Cleary", spotifyID: "1G6UgigP2liEHs6WpgugaJ", popularity: 18.0 },
{ artist: "Caroline Campbell", spotifyID: "4wSkTxCSZ0IWALAA43kbBk", popularity: 31.0 },
{ artist: "Randy Montana", spotifyID: "35a3DqXX4dNwDmgEzRJMDb", popularity: 21.0 },
{ artist: "Joseph Fennimore", spotifyID: "6onRAZRxCxHDbZ486I9Cdj", popularity: 0.0 },
{ artist: "Theo Hill", spotifyID: "0iPidq0YieRqMvjuKrInvL", popularity: 4.0 },
{ artist: "Eamonn McGirr", spotifyID: "1pwSCViuvWttoPmaKdLaeq", popularity: 0.0 },
{ artist: "Roger McNamee", spotifyID: "0m1ecnnimTJGYlO5Rv9KLc", popularity: 0.0 },
{ artist: "Stefon Harris", spotifyID: "4FDlrSZ3mEv5Jvn482sCbZ", popularity: 32.0 },
{ artist: "Mike Campese", spotifyID: "2RkYLR2TrdUp3Ur9WgrcfP", popularity: 1.0 },
{ artist: "Andy Paley", spotifyID: "2zPxitjqmY8tg0vwmTQPiQ", popularity: 0.0 },
{ artist: "Monster X", spotifyID: "7j0SIuT56cGF6nIbVmXB8B", popularity: 5.0 },
{ artist: "Sirsy", spotifyID: "4G1ItxIYGV6Zb7JjVWLxkb", popularity: 14.0 },
{ artist: "Mirk", spotifyID: "7uenKv56Ocb6iR7gCjWW2G", popularity: 6.0 },
{ artist: "Prince Daddy & The Hyena", spotifyID: "3EYgeLZ0vtVHKkUL26Eu49", popularity: 48.0 },
{ artist: "The Weasels", spotifyID: "71diBW7TpjOiQS05KcxYwE", popularity: 6.0 },
{ artist: "Clancy Newman", spotifyID: "59J9L4St1QsnJr6mK2WVW1", popularity: 0.0 },
{ artist: "Dave Parker", spotifyID: "6EL4GMFZh5vhWexb7k6knd", popularity: 0.0 },
{ artist: "Joe Kraemer", spotifyID: "1cqB0cMBR5OooKEEhRbWpl", popularity: 27.0 },
{ artist: "Jeremy James", spotifyID: "41FAFO0sEodQajiyqTtNX3", popularity: 27.0 },
]