const ashevilleNCArtists = [{ artist: "Luke Combs", spotifyID: "718COspgdWOnwOFpJHRZHS", popularity: 82.0 },
{ artist: "Rex Nelon", spotifyID: "1TQ9GpEp8dSBtNfijzya8w", popularity: 15.0 },
{ artist: "Eric Bachmann", spotifyID: "27CXUHv5mekE9LNdC1KEqb", popularity: 18.0 },
{ artist: "Bill Reynolds", spotifyID: "3cXgBTXRd1KhZzLgOfdRcq", popularity: 0.0 },
{ artist: "Rayna Gellert", spotifyID: "5hdTooIsiN2OmvS449nJNd", popularity: 24.0 },
{ artist: "Arthur Rice", spotifyID: "0XkbVzs6dEHQvpVzFRtVsF", popularity: 1.0 },
{ artist: "River Guerguerian", spotifyID: "2Ga2WaalQaFsz0d9dClJ8M", popularity: 3.0 },
{ artist: "Sons of Ralph", spotifyID: "6DHX9QBPPASC52cmSUMeRx", popularity: 3.0 },
{ artist: "Don Howland", spotifyID: "3q7VQ8Qo0jP8axnG8cNfur", popularity: 0.0 },
{ artist: "Caleb Johnson", spotifyID: "6PrHnMBRb8W0Uw4jMD5d8h", popularity: 23.0 },
{ artist: "Warren Haynes", spotifyID: "73iWh9WUMf0xK6cRkNJK4h", popularity: 47.0 },
{ artist: "Christine Kane", spotifyID: "524cQ8ZJgjm2cstwQUMyKG", popularity: 20.0 },
{ artist: "Squire Parsons", spotifyID: "1sqL1MIXvLtwUpiuX8NBxp", popularity: 28.0 },
{ artist: "Billy Jonas", spotifyID: "5BBnAQVthdgWecbXMRB7OS", popularity: 21.0 },
{ artist: "Kat Williams", spotifyID: "7LMoAXcawwnuR7IbpG9QmI", popularity: 1.0 },
{ artist: "Steven Heller", spotifyID: "7n9xJ7XOUCOGyqWzkhrAJK", popularity: 0.0 },
{ artist: "Toubab Krewe", spotifyID: "1jeEITLt57dM6g3JjToUmN", popularity: 35.0 },
{ artist: "David Wilcox", spotifyID: "3BTGj5kBXwkmm8M3vMbypx", popularity: 28.0 },
{ artist: "Bellamy Young", spotifyID: "15x0MUc2PQdUMjoPA33WSk", popularity: 7.0 },
{ artist: "Valorie Miller", spotifyID: "1TFFjkECJRxYyFpoWx7m4u", popularity: 0.0 },
{ artist: "Bryan Sutton", spotifyID: "1LFHqGsLJjUP2jqIAznlLm", popularity: 32.0 },
{ artist: "Chris Sharp", spotifyID: "5KB9lda5HGiGpANglJguYo", popularity: 0.0 },
{ artist: "Cameron Moore", spotifyID: "2j5pkQCefTANCr1NZuHT2M", popularity: 3.0 },
{ artist: "Root Boy Slim", spotifyID: "4t4obQquU1g9aEenSpQkBn", popularity: 5.0 },
{ artist: "Jermaine Dupri", spotifyID: "6nfYGe7IIuuP5bMY1jkJP6", popularity: 63.0 },
{ artist: "Chase Rice", spotifyID: "6pBNfggcZZDCmb0p92OnGn", popularity: 69.0 },
{ artist: "Mary Lattimore", spotifyID: "38MKhZmMRHAZRz8LqtKIBw", popularity: 43.0 },
{ artist: "Frances Nero", spotifyID: "5LyosPQrMqClLbNZGq9cie", popularity: 15.0 },
{ artist: "Backwards Sam Firk", spotifyID: "2BYy30VJA8Dg8KRPWdjZnL", popularity: 0.0 },
{ artist: "Tyler Ramsey", spotifyID: "1Ga71MIHyTN9VVuEtW57GK", popularity: 34.0 },
{ artist: "Lisa Bevill", spotifyID: "1bibdRQX7DtJj6Y6CU4Fpw", popularity: 12.0 },
]

module.exports = ashevilleNCArtists;