[{ artist: "Joe Albany", spotifyID: "31irFHg3rS596BJCLOroZ9", popularity: 20.0 },
{ artist: "Tasha Holiday", spotifyID: "6EVl1CXeN3s9xZNduHXcI1", popularity: 0.0 },
{ artist: "Chris Arena", spotifyID: "5X310IEeDgiwju1wQtukds", popularity: 19.0 },
{ artist: "Seth Justman", spotifyID: "20EcjmY2WLQZKpwIJ97n3p", popularity: 0.0 },
{ artist: "Paul Goldberg", spotifyID: "5mO6BtLsILnIGxIrygfpy2", popularity: 0.0 },
{ artist: "Harry Carroll", spotifyID: "08KEQZ7Z1uIpnjba8y8OjR", popularity: 2.0 },
{ artist: "Joseph Carleton Beal", spotifyID: "2bOIPACXYLIDtH1cP8g6wD", popularity: 1.0 },
{ artist: "Harvey Mason", spotifyID: "2MNNVXEpagQ3QWiOkXjQyT", popularity: 37.0 },
{ artist: "Bob Merrill", spotifyID: "2reXI3KyHPpMuNrXnnWmdR", popularity: 9.0 },
{ artist: "Nancy Falkow", spotifyID: "5xk4LaElu8oLUIKzKXxQ44", popularity: 1.0 },
{ artist: "Bruce Ditmas", spotifyID: "4gnLa5TVPbaMM1SngJQZqZ", popularity: 9.0 },
{ artist: "Joe McGinty", spotifyID: "74dI22iIWc1Q5jhHBPFzBV", popularity: 0.0 },
{ artist: "Sam Most", spotifyID: "6sMhcHW0oL5mjUPEnAHlYy", popularity: 7.0 },
{ artist: "Helen Forrest", spotifyID: "5SguMzNsojVk03s64Ggzad", popularity: 39.0 },
{ artist: "Patsy Garrett", spotifyID: "1vGRYoxaWL5fWIZw1sYOQE", popularity: 0.0 },
{ artist: "Jack Haley", spotifyID: "3GUMcKQJLVhhbFIYTSCVXp", popularity: 29.0 },
{ artist: "Eddie Collins", spotifyID: "7b3wRroXbzdJRumzStg63a", popularity: 10.0 },
{ artist: "Mary Stafford", spotifyID: "2gpf992SBo5JKP0WqVOWLb", popularity: 0.0 },
{ artist: "Jack Harrold", spotifyID: "0qi0bUTfst8govLzzcHKRs", popularity: 0.0 },
]