[{ artist: "Chuckie Campbell", spotifyID: "5KednZ2T0QlmOkff7nDtRK", popularity: 1.0 },
{ artist: "Ani DiFranco", spotifyID: "0AiTwNtYX8m4uhfU7rJ8RD", popularity: 53.0 },
{ artist: "Patrick Cowley", spotifyID: "1pggi3bfbAPkwrylE63MEO", popularity: 44.0 },
{ artist: "Frankie Dunlop", spotifyID: "5aX7oXHgxcRWdKGEsvgQkb", popularity: 2.0 },
{ artist: "William Christie", spotifyID: "7mkcqdifmNkhfJ7XZ7WFFS", popularity: 45.0 },
{ artist: "Terence Boylan", spotifyID: "7tEqcCZQ38VjTnpBVuRBoL", popularity: 12.0 },
{ artist: "Akir", spotifyID: "4OPwFSuypxZLw3ZL0Ei2UZ", popularity: 25.0 },
{ artist: "Lance Diamond", spotifyID: "7iliykALzYBdRCxUvYUxKd", popularity: 0.0 },
{ artist: "Adolph Deutsch", spotifyID: "5XfGFIgAuLp6WecQAJoIHJ", popularity: 19.0 },
{ artist: "Robert Kinkel", spotifyID: "6sjAnoKMPmwaPAzdPGaXWA", popularity: 0.0 },
{ artist: "Vaughn De Leath", spotifyID: "4oK3JPNyOedokore4DnIC0", popularity: 6.0 },
{ artist: "Marcus Goldhaber", spotifyID: "7Is5v9T0nFnfX4NwFD7446", popularity: 0.0 },
{ artist: "Harold Arlen", spotifyID: "7MOUyX1yT017l1Zt0mExIA", popularity: 32.0 },
{ artist: "Bobby Militello", spotifyID: "1g6mlFfY9TXI3bs5FioUZ4", popularity: 0.0 },
{ artist: "Jackson C. Frank", spotifyID: "5TNmizItgJPfvCoPKXAMGz", popularity: 47.0 },
{ artist: "Chris Barnes", spotifyID: "76k1J5QyTuYe1ee5GqQHlx", popularity: 2.0 },
{ artist: "Venetta Fields", spotifyID: "7IeO6oERTyshsLkQHOH0My", popularity: 1.0 },
{ artist: "Ray Henderson", spotifyID: "6sFuwIZlq0QRELXmWzMUkj", popularity: 13.0 },
{ artist: "Lou Courtney", spotifyID: "7fSioNqpL8eXp9IJoPcKP4", popularity: 9.0 },
{ artist: "Donnie Elbert", spotifyID: "2uA0g2bLN2rIGZDkx671Ig", popularity: 32.0 },
{ artist: "Vic Dana", spotifyID: "26LmRGHptm85F27BZwOSt7", popularity: 24.0 },
{ artist: "Eric Herman", spotifyID: "2yS5W7O7GJTcX68yyqK7rG", popularity: 8.0 },
{ artist: "Christina Courtin", spotifyID: "0HmtsxDaBnXPU0Lykw41f9", popularity: 3.0 },
{ artist: "Dave Fridmann", spotifyID: "0kydcbHRghva5MNR87jLS0", popularity: 19.0 },
{ artist: "Emile Haynie", spotifyID: "3HlAg5EbFYOdlVPooU9f0K", popularity: 38.0 },
{ artist: "Teddy Geiger", spotifyID: "1YIpZOfyHXMUgUaxxxgbaC", popularity: 42.0 },
{ artist: "Elizabeth Koch", spotifyID: "1gDy83TuP4FUI09aupZ0Dq", popularity: 0.0 },
{ artist: "Lisa Kindred", spotifyID: "1LsZbZFFlrNjXZIoNOI419", popularity: 5.0 },
{ artist: "DW", spotifyID: "5r1dLTL180wNTOpeqwClIf", popularity: 16.0 },
{ artist: "Dodo Greene", spotifyID: "0xsOiyQADUzVWVginIMzQu", popularity: 6.0 },
{ artist: "Ray Kennedy", spotifyID: "6CPNVbAOtmZGh4N2PHZRQe", popularity: 15.0 },
{ artist: "Tom Hambridge", spotifyID: "0lSfDpkGWg4jhiX6xoslu6", popularity: 14.0 },
{ artist: "Brian McKnight", spotifyID: "6k0IBR0lU42s2GYpNX7kA9", popularity: 65.0 },
{ artist: "Gurf Morlix", spotifyID: "6ojLnwwSb9VwXV4b1iAw5X", popularity: 28.0 },
{ artist: "Rick James", spotifyID: "0FrpdcVlJQqibaz5HfBUrL", popularity: 62.0 },
{ artist: "Jim Hall", spotifyID: "5pMmqpG3HsoJ6EDDoXGXEr", popularity: 54.0 },
{ artist: "Sherrie Maricle", spotifyID: "7f7PWUH3CnHbQbKLAYms7t", popularity: 3.0 },
{ artist: "Michael O'Mara", spotifyID: "6tKkT6STSxdeTPfVwzOBT6", popularity: 0.0 },
{ artist: "Michael Pisaro", spotifyID: "3nvY4EGMTXc3TM6m7oKaRb", popularity: 11.0 },
{ artist: "David Lucas", spotifyID: "08qtm0YSyiO66n1imbgqDl", popularity: 5.0 },
{ artist: "Jason Vieaux", spotifyID: "0wHPFvTTjnGMQ6bvUn2KlO", popularity: 34.0 },
{ artist: "Valerian Ruminski", spotifyID: "0NDADnSAt5df4c7W5hlC1S", popularity: 0.0 },
{ artist: "Mary Ramsey", spotifyID: "7xrAtSV4GmLu0ceCC4qBpN", popularity: 1.0 },
{ artist: "Joe Kraemer", spotifyID: "1cqB0cMBR5OooKEEhRbWpl", popularity: 26.0 },
{ artist: "Carol Wincenc", spotifyID: "6a74be3DKWOgg8MAMGMB8Z", popularity: 19.0 },
{ artist: "Dave Schulz", spotifyID: "2SNZht5DfRimAcftxUyasT", popularity: 0.0 },
{ artist: "Paul Siebel", spotifyID: "5EB5q368CZpEhSbLIVIAXh", popularity: 9.0 },
{ artist: "Harry B. Smith", spotifyID: "4l19tDzT5qXCnqyHKvINJS", popularity: 8.0 },
{ artist: "Steve Nathan", spotifyID: "6UERPNj0UcCVlZpLRErgeR", popularity: 0.0 },
{ artist: "Grasshopper", spotifyID: "5IxPdROZmnCyD6TBuSJMYE", popularity: 42.0 },
{ artist: "Greg Leisz", spotifyID: "5OslOE4iegsG2uqyOZJ2OU", popularity: 25.0 },
{ artist: "Gary Mallaber", spotifyID: "201l45QJnjZsaujpj24bRv", popularity: 0.0 },
{ artist: "Billy Sheehan", spotifyID: "0GXvIHZC6fUFoclPbf7Lbm", popularity: 26.0 },
{ artist: "Mark Russell", spotifyID: "37l5yG7l2E6o7BZpMp2xda", popularity: 2.0 },
{ artist: "John Rzeznik", spotifyID: "4HQjQ1pCcv25LRqTxWKN4t", popularity: 40.0 },
{ artist: "Ronnie Foster", spotifyID: "4B5XByhwtjsqGxs91fYMhZ", popularity: 35.0 },
{ artist: "Eugene Stratton", spotifyID: "4dnQEKJP5sli2dvCYIdCHL", popularity: 1.0 },
{ artist: "Lucky Peterson", spotifyID: "3OxsMm9KHw2FRJLGHtILl5", popularity: 38.0 },
{ artist: "Grover Washington Jr.", spotifyID: "05YVYeV4HxYp5rrWalvuE1", popularity: 56.0 },
{ artist: "David Shire", spotifyID: "5M0BsKplclHv3l6QjOpotN", popularity: 33.0 },
{ artist: "Willie Nile", spotifyID: "42chtGdwnAdG2TECndse7J", popularity: 26.0 },
{ artist: "DM Stith", spotifyID: "63JafnzstkiEySBh4rBiCM", popularity: 18.0 },
{ artist: "Mike Terrana", spotifyID: "4AtQAZV0RUOpCHa20mTWp4", popularity: 12.0 },
{ artist: "Robby Takac", spotifyID: "2VYwa2ah7zx9nF8EHo8UHk", popularity: 0.0 },
{ artist: "Westside Gunn", spotifyID: "0ABk515kENDyATUdpCKVfW", popularity: 53.0 },
{ artist: "Tom Schuman", spotifyID: "4UiNTnkjaAWssEqZbtVUb5", popularity: 7.0 },
{ artist: "Leonard Pennario", spotifyID: "0dm9wL4PQ7dmrsiyArDWTt", popularity: 22.0 },
{ artist: "Mel Lewis", spotifyID: "6tWRPRLzfmckBpyR8g4Nnw", popularity: 28.0 },
{ artist: "Paul Moravec", spotifyID: "2YZmIRpxILQkI2jteKnLPL", popularity: 10.0 },
{ artist: "Cory Wells", spotifyID: "4iLkUR4VnW577DOxOYjxwG", popularity: 41.0 },
{ artist: "Patrick Wilson", spotifyID: "7JDIzsiYm1WS3zUpiTdW52", popularity: 50.0 },
{ artist: "Marc Scibilia", spotifyID: "4CHiVarfTsFhkFOk5vHS77", popularity: 54.0 },
{ artist: "Clint Holmes", spotifyID: "5gwLOQFOJ2lFtDKuxho9U1", popularity: 17.0 },
{ artist: "Lejaren Hiller", spotifyID: "0omZcKDW135PuuBtAiMMLL", popularity: 0.0 },
{ artist: "Herbert Witherspoon", spotifyID: "2Fu75mEwtlk5BdfhNDharU", popularity: 0.0 },
{ artist: "Stevie J", spotifyID: "61hrhoOBeupAeXFJeYhDGn", popularity: 23.0 },
{ artist: "Peter Case", spotifyID: "771bZ8ZHkvOqkI7baL68X3", popularity: 19.0 },
{ artist: "John Stevens", spotifyID: "4EW7CE2HetO7GkDEOYDrXF", popularity: 19.0 },
{ artist: "Tony Terran", spotifyID: "3iOv16Uj8JUhGVLesSbe3Z", popularity: 0.0 },
{ artist: "Joanie Sommers", spotifyID: "64ZUngtVBOg6z3kKagoZhU", popularity: 23.0 },
{ artist: "Sylvain Sylvain", spotifyID: "0IfkFoyLbsgahVvNfPnV2y", popularity: 42.0 },
{ artist: "Pamela Z", spotifyID: "05cGsE3L2JX7Tc1auPVQZa", popularity: 4.0 },
{ artist: "Z. Mann Zilla", spotifyID: "3cQXr8INoXGC7qc0Kdgbka", popularity: 0.0 },
]