const camdenNJArtists = [{ artist: "Cindy Birdsong", spotifyID: "0gzqkXQkRXNVDIyJXET3Gr", popularity: 0.0 },
{ artist: "Rachel Gould", spotifyID: "54SWsJGcDkT1IzhHhQNHje", popularity: 1.0 },
{ artist: "Lola Falana", spotifyID: "2nKM2mqeHqKTCnI1abFbYh", popularity: 0.0 },
{ artist: "Christine Andreas", spotifyID: "5cxl2myOakg9OH8q7nh1th", popularity: 22.0 },
{ artist: "Russ Columbo", spotifyID: "1bX7fjOYkonAk4NR2S82Kw", popularity: 23.0 },
{ artist: "Jim Perry", spotifyID: "7c74iyd0p6Z4ODuHKRmaRD", popularity: 0.0 },
{ artist: "Graham Alexander", spotifyID: "2axdATDyHbmHsKQCC4sHea", popularity: 0.0 },
{ artist: "Nick Douglas", spotifyID: "1QhhIRmF6gvb7zMkX0ZNGE", popularity: 0.0 },
{ artist: "Cary Gilbert", spotifyID: "0jiFRizUjRdn5bk0NJ5URG", popularity: 5.0 },
{ artist: "Frank Tiberi", spotifyID: "4c0kCxkNrAZlIeI80iLdKY", popularity: 3.0 },
{ artist: "Richard Sterban", spotifyID: "68R0FlQ2W6NviDzqVc2P7k", popularity: 3.0 },
{ artist: "Paul Baloche", spotifyID: "1jH3GuQCPI87UrS0hcScHr", popularity: 47.0 },
{ artist: "William Hung", spotifyID: "3bU97PoqnxjKD45CrfwmC9", popularity: 17.0 },
{ artist: "Barbara Ingram", spotifyID: "471L2JqLMIpIqx5cNF7NiX", popularity: 0.0 },
{ artist: "Heather Henderson", spotifyID: "0Cj6ALhuW3UC3QuCEHuvR1", popularity: 0.0 },
{ artist: "Michael Lisicky", spotifyID: "5JA4KXOo6pdtctZZd8Dkro", popularity: 0.0 },
{ artist: "Lady Crush", spotifyID: "3Kc3yciTwK1ZITadYlIQRW", popularity: 0.0 },
{ artist: "Buddy DeFranco", spotifyID: "4PGmuM1NRpb2AynvthlC6y", popularity: 23.0 },
{ artist: "Buster Williams", spotifyID: "0pSoLnWrkv4lvm0CBl526G", popularity: 17.0 },
{ artist: "Tye Tribbett", spotifyID: "1xy9x7h2jKEg8iG22Sml32", popularity: 52.0 },
{ artist: "Jack Vees", spotifyID: "1Z53ZGaoOF0jyDDG7c5yJs", popularity: 0.0 },
{ artist: "Richard Holmes", spotifyID: "7izkpvBGc31hUccjdSNz8k", popularity: 27.0 },
{ artist: "Eric Lewis", spotifyID: "5hmxB1UVMeseEo5DMG1ykc", popularity: 8.0 },
{ artist: "Wayne Dockery", spotifyID: "0hkvwgevvQMyRaMMBVzzHp", popularity: 4.0 },
{ artist: "Ronny J", spotifyID: "3TKCdsX8yNNoiC1gesn6or", popularity: 60.0 },
{ artist: "Jersey Surf Drum and Bugle Corps", spotifyID: "5qutFiBjC5IidIaKnGpi7N", popularity: 0.0 },
{ artist: "Anna Sosenko", spotifyID: "6McscrthMgLjcwzmXQlRdd", popularity: 0.0 },
{ artist: "Jus Allah", spotifyID: "1rpmyC5KVfoFqkNHKkSTXf", popularity: 36.0 },
]

module.exports = camdenNJArtists;