[{artist:"DaBaby",spotifyID:"4r63FhuTkUYltbVAg5TQnk",popularity:88.0},
{artist:"Banknote Mitch",spotifyID:"69AFWtsDeUbtcJE0RHioU8",popularity:0.0},
{artist:"Travis Greene",spotifyID:"22JNV0JWTJkY1qzKJhxdRe",popularity:56.0},
{artist:"Deniro Farrar",spotifyID:"3xXtYXTUWYuJpJXub1Up5p",popularity:43.0},
{artist:"Benji Hughes",spotifyID:"1w4UUVXVsk63VT2vTwx1e1",popularity:37.0},
{artist:"Frankie Mann",spotifyID:"0jmJE0UcA2Ngp9qXYiGqsM",popularity:2.0},
{artist:"Dan Locklair",spotifyID:"5GRceTPo6rnCpddIi4QMM1",popularity:12.0},
{artist:"Sammy Johns",spotifyID:"5L2UqkzpfZD5OpdA6fSfVH",popularity:31.0},
{artist:"Andy Cherry",spotifyID:"67xUi7je7BPGgGdem8oycN",popularity:23.0},
{artist:"Shareefa",spotifyID:"6PCMMSSuTf9iCVVxYru5XI",popularity:26.0},
{artist:"Jack Lawrence",spotifyID:"0sBKkpFqxsLg0Ao6924RHK",popularity:31.0},
{artist:"Tim Cashion",spotifyID:"1RbZ6ILsNOb4eQPeN3Ceh6",popularity:0.0},
{artist:"Patrick Love",spotifyID:"3AWctn8IqczGFgBtAmnrQJ",popularity:10.0},
{artist:"Scarlett Cherry",spotifyID:"7r8NUKg8FDTgdTh0oeCP0q",popularity:9.0},
{artist:"Kelsey Lu",spotifyID:"0fEfMW5bypHZ0A8eLnhwj5",popularity:54.0},
{artist:"Catherine Popper",spotifyID:"1f60QOQYiIYT1hejQ7zNYe",popularity:5.0},
{artist:"Prairie Prince",spotifyID:"6KysYJ3z5IFMYJLCBPUzSs",popularity:3.0},
{artist:"Nappy Brown",spotifyID:"7oR6vQt8KT2ZWUpC65jTha",popularity:29.0},
{artist:"Mia Sable",spotifyID:"5S46vcuQpjL4dqu3wawCVm",popularity:12.0},
{artist:"The Catalinas",spotifyID:"7D0l1Vpu9Lj8TZwcs6fFjs",popularity:9.0},
{artist:"Tyrone Jefferson",spotifyID:"5nNIQuMHx7o19mFvWmTfQU",popularity:4.0},
{artist:"Seth Avett",spotifyID:"6XCZ1uSV9jKMOlqck0ubQW",popularity:37.0},
{artist:"Cameron Moore",spotifyID:"2j5pkQCefTANCr1NZuHT2M",popularity:3.0},
{artist:"Loonis McGlohon",spotifyID:"58ivNIFWjJ24WqtZFAbWte",popularity:4.0},
{artist:"Claire Ritter",spotifyID:"6oAwSlxigJIKlledlEBjXF",popularity:1.0},
{artist:"Anthony Hamilton",spotifyID:"2DzRMyWgjuMbYvt5BLbpCo",popularity:62.0},
{artist:"Don Dixon",spotifyID:"3LdLKmvFl65YydnIc2ZA9c",popularity:4.0},
{artist:"Eileen Rodgers",spotifyID:"5U6AFHwdlMoOHEPmRQxTsN",popularity:14.0},
{artist:"Of Good Nature",spotifyID:"76TaiIXCKLs7UeOOwghV7c",popularity:29.0},
{artist:"David Vincent",spotifyID:"2F9yvepnWbliXYgnMfaeoT",popularity:3.0},
{artist:"Hope Nicholls",spotifyID:"7CDd7LlieeMYm5nxApqRbs",popularity:0.0},
{artist:"Simplified",spotifyID:"25IYFyXjuCqKlIbSeaRAZO",popularity:40.0},
{artist:"Jon Woods",spotifyID:"5LzsN4KaYvUXAiZlAZ5iuC",popularity:25.0},
{artist:"John Scott Trotter",spotifyID:"735L650pvygCZZlPMyHqsN",popularity:41.0},
{artist:"Mike City",spotifyID:"4b8jP3BNzAfeaKqd4Whlvd",popularity:36.0},
{artist:"Michael Colina",spotifyID:"1n4uiCu9w78PO9z7OnH9sW",popularity:0.0},
{artist:"Danny Thomas",spotifyID:"4w9baWHjc6mDIyAsGPQ5Cr",popularity:15.0},
{artist:"Lena Wilson",spotifyID:"0mmKZiVInEE97zsIRniGKF",popularity:0.0},
{artist:"LeJuene Thompson",spotifyID:"2DlJnIo9YqvFVIFrLuqzxC",popularity:22.0},
{artist:"Wilbert Harrison",spotifyID:"7rETVFaF9VOFPmmzsY3kO6",popularity:34.0},
{artist:"Wally Shoup",spotifyID:"29srNMCV5i7Os71GfoOvrZ",popularity:0.0},
{artist:"Marie Hines",spotifyID:"60lN4NCcmjNkw5of3roHxk",popularity:27.0},
]