[
    {artist:"John William Boone",spotifyID:"6KX8ih5AqgmV8Ms0RiJ7cB",popularity:0.0},
    {artist:"Esterhazy Quartet",spotifyID:"3rN1deoqD3RoK1DH0XEEpN",popularity:0.0},
    {artist:"Andrew VanWyngarden",spotifyID:"0SZWZaoD3G4jMjGPEB1IiG",popularity:26.0},
    {artist:"The Hooten Hallers",spotifyID:"7AtcML9ORkrIUVvpdPHyo9",popularity:23.0},
    {artist:"Columbia Chorale",spotifyID:"1s7C3OoBR7UY1tkO1B5FYQ",popularity:0.0},
    {artist:"Marching Mizzou",spotifyID:"6VNgXtXFzC7fXQ7mShd5KL",popularity:7.0},
    {artist:"Nick Jameson",spotifyID:"5WsW78tOdOTN3Rt4E8WQOt",popularity:1.0},
    {artist:"Deke Dickerson",spotifyID:"6Uhcb4YBtQmZJKL3jBpPX4",popularity:22.0},
    {artist:"Walt Koken",spotifyID:"6B147DYqGI7lyugDs5IVb3",popularity:7.0},
    {artist:"Jane Froman",spotifyID:"6NY3765DltvFLSQ1be9cHC",popularity:12.0},
    {artist:"Brett James",spotifyID:"62T3HAeguSoE6yzZIv3UaR",popularity:16.0},
    {artist:"Stevie Stone",spotifyID:"2IvPBSC4CgNLYC1GHEAxcN",popularity:51.0},
    {artist:"Korla Pandit",spotifyID:"5s2iRBZgWm3LHYiU8TGBJY",popularity:10.0},
]
