[{ artist: "Gordon MacRae", spotifyID: "3dvIPsJH7o9xnBwFxowzof", popularity: 35.0 },
{ artist: "Queen Latifah", spotifyID: "5m7wCUhYhBh7A3A3YMxrbt", popularity: 58.0 },
{ artist: "Treach", spotifyID: "3b3teOkAyYfhj4xiMvqYvW", popularity: 33.0 },
{ artist: "Bill Chinnock", spotifyID: "4gl3qjGVkweASR3WvcO7Wv", popularity: 5.0 },
{ artist: "Naturi Naughton", spotifyID: "56RnObLA96CLXUOpCi7WhC", popularity: 29.0 },
{ artist: "Edward Meeker", spotifyID: "2bXgUrF2xgiSYS85RsEv5U", popularity: 1.0 },
{ artist: "14 Karat Soul", spotifyID: "28LoPvmyYI8JJlnXAZbmiJ", popularity: 2.0 },
{ artist: "Philip Egner", spotifyID: "18ZsA2qzUcAsc80q8OwLQ4", popularity: 0.0 },
{ artist: "Frances Day", spotifyID: "0Np8kbarcruI1MELpnzbex", popularity: 1.0 },
{ artist: "Janis Ian", spotifyID: "5c9uFWpZY2MTlk7Rft0tgp", popularity: 44.0 },
{ artist: "John Mooney", spotifyID: "06qu5apaO4yt4gBL4G5F2J", popularity: 22.0 },
{ artist: "Robert David Hall", spotifyID: "5W4w8o6jZK2X95HIIUW5Ww", popularity: 0.0 },
{ artist: "Dionne Warwick", spotifyID: "2JSjCHK79gdaiPWdKiNUNp", popularity: 63.0 },
{ artist: "Whitney Houston", spotifyID: "6XpaIBNiVzIetEPCWDvAFP", popularity: 82.0 },
{ artist: "Kerri Chandler", spotifyID: "7nqpEU6DCHkNtK1bYsyS3W", popularity: 44.0 },
{ artist: "Cevin Fisher", spotifyID: "2KKgW6x86NOhIJnMlxFD1u", popularity: 41.0 },
{ artist: "Cozy Cole", spotifyID: "6fkwnXeEKj729M5HSIaoMr", popularity: 12.0 },
{ artist: "Slide Hampton", spotifyID: "1JrZuQYlOzhNj1nvlB0Yys", popularity: 41.0 },
{ artist: "Shareefa", spotifyID: "6PCMMSSuTf9iCVVxYru5XI", popularity: 26.0 },
{ artist: "Bill Ware", spotifyID: "3D34yeE2dyhGvzinxRTsup", popularity: 16.0 },
{ artist: "Antonique Smith", spotifyID: "4h6ZCTKha4MPmhpxYUs7E5", popularity: 17.0 },
]