[{ artist: "Harold Adamson", spotifyID: "4aPdXwJ0VY9ZWhTiMS0vei", popularity: 4.0 },
{ artist: "Al Caiola", spotifyID: "1kiuYnpzdoWeSpdHObdhQ6", popularity: 36.0 },
{ artist: "Chill Rob G", spotifyID: "7rQ0Kt1wAU7IU3VpciuuXr", popularity: 10.0 },
{ artist: "Chris Phoenix", spotifyID: "0QXIl1ixPdgnBTk98N4gVd", popularity: 0.0 },
{ artist: "Beth Fowler", spotifyID: "7KNW6OwcA260MsaEtnvhxV", popularity: 49.0 },
{ artist: "Sonny Igoe", spotifyID: "6NkUc9PPnaBwPqp1h2MCIL", popularity: 0.0 },
{ artist: "Cy Coben", spotifyID: "299AU7SVtpRzefsiUkmAZj", popularity: 0.0 },
{ artist: "Don Ciccone", spotifyID: "1fw5Y32oLHIif2ZpkcIG6Q", popularity: 0.0 },
{ artist: "Joe Budden", spotifyID: "1SAugjIcuwNPKS4urSB7A6", popularity: 53.0 },
{ artist: "Phyllis Newman", spotifyID: "5Nkn9Bo6iFZg7GtawefqnY", popularity: 1.0 },
{ artist: "The Duprees", spotifyID: "6nYTjfJFNic9m83TROYHUS", popularity: 35.0 },
{ artist: "Luke Elliot", spotifyID: "7t6cXssTAtfc6F316tvLv7", popularity: 19.0 },
{ artist: "Dickie Thompson", spotifyID: "1A0xlRpXWKhPVyEqiZbVKG", popularity: 0.0 },
{ artist: "Ronnie & the Hi-Lites", spotifyID: "22Evjdbqf28wiTLKbp7CsQ", popularity: 0.0 },
{ artist: "Peter Lemongello", spotifyID: "07g1zY8FfmpMnhII5lJT00", popularity: 3.0 },
{ artist: "Al Di Meola", spotifyID: "3bBWKHfpepPOychRNFzg4q", popularity: 45.0 },
{ artist: "Jerry Herman", spotifyID: "4GBe6ctpZMwMbaRb9KZrNU", popularity: 35.0 },
{ artist: "Kit McClure", spotifyID: "3Mk2rtitFlCWeIwgQFkXPk", popularity: 1.0 },
{ artist: "Mimi Jones", spotifyID: "7hZaSxRUXwteKsph6zGfr6", popularity: 0.0 },
{ artist: "P.M. Dawn", spotifyID: "5DgjOwTN6o76J5Gf8MzEoL", popularity: 45.0 },
{ artist: "Tia Fuller", spotifyID: "3SMDloWrQhtfY0KsPQ1qql", popularity: 15.0 },
{ artist: "Tris McCall", spotifyID: "4sQPLrLjorWkx7FGC33PYp", popularity: 0.0 },
{ artist: "Christina Milian", spotifyID: "4eAOcbAXIF4BmbN6E1QIlw", popularity: 54.0 },
{ artist: "Marilyn McCoo", spotifyID: "2jirMwr4cHJzjtx8vDX5IO", popularity: 34.0 },
{ artist: "Gerry Rosenthal", spotifyID: "7r6lZxLwtZsaPltN7kSDTO", popularity: 0.0 },
{ artist: "Frank Sinatra Jr.", spotifyID: "5fElZYhQFp0lEc4FQVcRu1", popularity: 29.0 },
{ artist: "Akon", spotifyID: "0z4gvV4rjIZ9wHck67ucSV", popularity: 79.0 },
{ artist: "Will Oakland", spotifyID: "7aoyGipPQaCvDTrJIe49W8", popularity: 0.0 },
{ artist: "Andrew Hill", spotifyID: "4ORSNkNYSzva169PBZCzvy", popularity: 30.0 },
{ artist: "Philip James", spotifyID: "7G03RCcJlEJkl8GrNY5szK", popularity: 7.0 },
{ artist: "Brute Force", spotifyID: "05UtcYF5Ti4z9cQN4GZJ8v", popularity: 14.0 },
{ artist: "Maury Yeston", spotifyID: "0RSFYUQQWpZg5bOne6OuzD", popularity: 30.0 },
{ artist: "Jack Frost", spotifyID: "3f4jpufkQoh1yCyPb8589b", popularity: 24.0 },
{ artist: "Nancy Sinatra", spotifyID: "3IZrrNonYELubLPJmqOci2", popularity: 63.0 },
{ artist: "Trés Hanley", spotifyID: "7kd3iuzUsWcJyrYWXAvWHR", popularity: 0.0 },
{ artist: "Phil Urso", spotifyID: "4BBgtSaiKVW1l5MI2k6K9l", popularity: 12.0 },
{ artist: "Richie Havens", spotifyID: "4Qk0lWGeXydDvfrDufDQ9p", popularity: 49.0 },
{ artist: "Tommy West", spotifyID: "3s0krB7kVIw0i6eozqdQus", popularity: 13.0 },
{ artist: "Tom Tallitsch", spotifyID: "74CViUznlPPaXB7eZXm1Pz", popularity: 2.0 },
{ artist: "Peter Sliker", spotifyID: "7spzCmiehyMROuQRFMYwm0", popularity: 1.0 },
{ artist: "Rob Mazurek", spotifyID: "7uWd7df9GwjSZqo1cVF7Qs", popularity: 5.0 },
{ artist: "Ed Shaughnessy", spotifyID: "4Yb3PUuXRbjrn0PkvzsJdv", popularity: 2.0 },
{ artist: "Diana Soviero", spotifyID: "6QHs74FJnTv3cYctcJ2KlH", popularity: 3.0 },
{ artist: "David Kikoski", spotifyID: "11c9fr8DFDGQZ1Cv77L8PW", popularity: 19.0 },
{ artist: "Apache", spotifyID: "1veLiIQBt4YcFO5Z36DwFO", popularity: 54.0 },
]