const kansasCityMOArtists = [{ artist: "Matt Gilman", spotifyID: "73hSbuO7zeiAnHpkyhQN5P", popularity: 50.0 },
{ artist: "Robert Russell Bennett", spotifyID: "52SryVadriXLIyUJx3pU9Q", popularity: 21.0 },
{ artist: "Alex Bailey", spotifyID: "3089cfbw81D49XhuMRcyQD", popularity: 1.0 },
{ artist: "Carol Duboc", spotifyID: "4MZOTmZxvF4s1ZwnDH1Hsf", popularity: 19.0 },
{ artist: "Frank Butler", spotifyID: "6rebkw7hosc1z7AGhonnDi", popularity: 12.0 },
{ artist: "Gene McDaniels", spotifyID: "6I7tqjEzznFPrardDfvsvq", popularity: 25.0 },
{ artist: "Ahmad Alaadeen", spotifyID: "029UfQLsiTyC1khE7706VO", popularity: 0.0 },
{ artist: "Samantha Fish", spotifyID: "5HsS48kuvghKcNpwOaAvB5", popularity: 45.0 },
{ artist: "Michelle Anthony", spotifyID: "2LHouz8OHFRDVub8UPaz66", popularity: 0.0 },
{ artist: "Wayne Nelson", spotifyID: "3MGasL0pEiC1xsLo5wnCCa", popularity: 0.0 },
{ artist: "Vinson Cole", spotifyID: "2j6cP3f3TxyHzcKdWYSm6h", popularity: 35.0 },
{ artist: "Chris Connor", spotifyID: "5Q6PVXflC7LKN42bYupRJQ", popularity: 27.0 },
{ artist: "Bob Brookmeyer", spotifyID: "3aM9H4QBnPUo6mnNVufAtN", popularity: 50.0 },
{ artist: "John Kander", spotifyID: "7xSEQmlssbeoIUdQ0HFjUT", popularity: 32.0 },
{ artist: "Max Bennett", spotifyID: "0a9O9ybFqfYAqu0TgbJVxC", popularity: 3.0 },
{ artist: "Thomas Hayward", spotifyID: "1F8GknDXigHszmYVRBGIC5", popularity: 5.0 },
{ artist: "Dana Cooper", spotifyID: "2QsB7oobOWcxoCV7eJjPaa", popularity: 3.0 },
{ artist: "Jeff Black", spotifyID: "4c1eDydx9m0UwoT4sztU4J", popularity: 12.0 },
{ artist: "Melora Creager", spotifyID: "7zi7uAOt39Ncfp7yTw7zcA", popularity: 11.0 },
{ artist: "Norman Brown", spotifyID: "79kOOyVKcrCOKDnzcDHsia", popularity: 51.0 },
{ artist: "Carl Busch", spotifyID: "7KkkWLRV6IHJGLzfYNQBAA", popularity: 0.0 },
{ artist: "Harold Ashby", spotifyID: "5UWVQaRM37F2PNcWuPPiY2", popularity: 9.0 },
{ artist: "Kevin Morby", spotifyID: "6fxk3UXHTFYET8qCT9WlBF", popularity: 59.0 },
{ artist: "Marilyn Maye", spotifyID: "2t3QtAfLrYWErvBCi3Bgfv", popularity: 12.0 },
{ artist: "Emma Lou Diemer", spotifyID: "1LHzEIV8QFpmud6vmgaNWl", popularity: 4.0 },
{ artist: "Jim Lang", spotifyID: "1JgLaQ1Bwzy7Znnza9kYOw", popularity: 17.0 },
{ artist: "Paul Clark", spotifyID: "0U6pPXP2Z31pdhWYLLUxKU", popularity: 13.0 },
{ artist: "Jessica Harp", spotifyID: "2DtEjX1i4Vs7Gs1gADNiWj", popularity: 13.0 },
{ artist: "Jimmy Beasley", spotifyID: "0kULVdibEFp7vwSwe8lfEb", popularity: 2.0 },
{ artist: "Lottie Kimbrough", spotifyID: "34x3BPBKFmYML037CxIwCb", popularity: 3.0 },
{ artist: "David Bennett", spotifyID: "3QOU7sPup7JU8l8vqqi01H", popularity: 16.0 },
{ artist: "Amanda Fish", spotifyID: "4qwViea6D8YuylgvWoqFIa", popularity: 9.0 },
{ artist: "Burt Bacharach", spotifyID: "35y7CZMg7jbG8Q96JY7dyC", popularity: 49.0 },
{ artist: "Chris Cobbins", spotifyID: "6WtrY6QGqSHWgJMRVn6lAk", popularity: 28.0 },
{ artist: "Shae Jones", spotifyID: "5qtdcfmOeoM8S9IdhvGlXG", popularity: 10.0 },
{ artist: "James Gadson", spotifyID: "13dU3pLOyxMY7WOtFSZQZJ", popularity: 35.0 },
{ artist: "Kevin Mahogany", spotifyID: "7sJEt4QPDYhjJ9tcHSlhhN", popularity: 35.0 },
{ artist: "Lonnie McFadden", spotifyID: "5ZCt2KB8f8ogcLK9Qbx3he", popularity: 2.0 },
{ artist: "Basil Poledouris", spotifyID: "4jF9GaNGCGBeu2nKqFZ1K0", popularity: 45.0 },
{ artist: "Sean Ingram", spotifyID: "1nD9q6UrFfxSvPH8TeIEsG", popularity: 0.0 },
{ artist: "Melba Liston", spotifyID: "45KruXC5hUtqfCQsbD5xP0", popularity: 8.0 },
{ artist: "Tom Shapiro", spotifyID: "2HDI1OwdsxJ14F4p95OWdg", popularity: 0.0 },
{ artist: "William Matthews", spotifyID: "6xzvt1VigDuN3Qt39YozYA", popularity: 46.0 },
{ artist: "Lee McBee", spotifyID: "5BaFHawJB3tPavc4XqjwZW", popularity: 2.0 },
{ artist: "Billy Mitchell", spotifyID: "1M5tpCHilgyeT9aXu1J9Ib", popularity: 9.0 },
{ artist: "Lady Bianca", spotifyID: "5CrJ7LQ6nKdLZAS4wHmiov", popularity: 2.0 },
{ artist: "John Patton", spotifyID: "4BXF9pCPS864m8VMjuR4Pl", popularity: 28.0 },
{ artist: "Chuck Norris", spotifyID: "2HQMxIoCLgkUbW66GuVX1m", popularity: 22.0 },
{ artist: "Kelley Hunt", spotifyID: "0L7Y276gBjB2pxuyhpgzgv", popularity: 24.0 },
{ artist: "Charlie Parker", spotifyID: "4Ww5mwS7BWYjoZTUIrMHfC", popularity: 53.0 },
{ artist: "Sada K.", spotifyID: "6jFgqyc7ZSTSwIQFotdGHd", popularity: 10.0 },
{ artist: "Jerry Vandiver", spotifyID: "4iFMZHjMRHfOCP5wNupSq5", popularity: 4.0 },
{ artist: "Tevin Thomas", spotifyID: "658jpgfVHwl3kfeibER9YX", popularity: 0.0 },
{ artist: "Dustin Smith", spotifyID: "2VKhyPoqHFaT4Ci68cTGVa", popularity: 33.0 },
{ artist: "Mark Spoelstra", spotifyID: "1YfYCpbdjUOzremMD0KqXi", popularity: 5.0 },
{ artist: "Alexis Spight", spotifyID: "60TmfPS3h98rLg7M2nTmlX", popularity: 27.0 },
{ artist: "Ben Ryan", spotifyID: "1dShVzggAwFJFOo2N9RFQB", popularity: 20.0 },
{ artist: "Pete Johnson", spotifyID: "7l71rXhsmDwoDgbyXDadtZ", popularity: 20.0 },
{ artist: "Herb Reed", spotifyID: "60M7tXOHeqMrb4UwBwbsNm", popularity: 0.0 },
{ artist: "Skatterman", spotifyID: "7j737JHxqSvr0ELJXhHgNq", popularity: 41.0 },
{ artist: "Lucian Piane", spotifyID: "27x5boWqlA0tWUHq9F1UPb", popularity: 45.0 },
{ artist: "Von Smith", spotifyID: "54vTuvEhI9EslkbBqsdb4l", popularity: 41.0 },
{ artist: "Eldar Djangirov", spotifyID: "7oOc9wIfiBHYBs6PC83vIW", popularity: 31.0 },
{ artist: "Big Joe Turner", spotifyID: "1DTgcOxytJHD8p17mhSgd7", popularity: 41.0 },
{ artist: "Dana Suesse", spotifyID: "7z6gHumB3WriLbqxXN1Gp8", popularity: 5.0 },
{ artist: "Bennie Moten", spotifyID: "1bm4KifyNLFa4pjZzulTQU", popularity: 14.0 },
{ artist: "Jon Thurlow", spotifyID: "5o0OkYkblxitp1gdPiZO0B", popularity: 37.0 },
{ artist: "Actors&Actresses", spotifyID: "2Vm9wd6V6YyLAxjvf3RCkM", popularity: 0.0 },
{ artist: "The ACBs", spotifyID: "1F8vP4g2sthItVGXVTymxo", popularity: 17.0 },
{ artist: "Krizz Kaliko", spotifyID: "3SEJQy90Vgg1aSnZ9b4AU9", popularity: 61.0 },
{ artist: "Virgil Thomson", spotifyID: "1ucvqiCLdOj84dNEKXS5mr", popularity: 15.0 },
{ artist: "Sandra Warfield", spotifyID: "3TWJg7DSIUPM3RgDO5R5la", popularity: 2.0 },
{ artist: "Danielle Nicole", spotifyID: "34mu675oQQ5ZNuK1soZrIn", popularity: 36.0 },
{ artist: "Logan Richardson", spotifyID: "0SPbho0MYZZGtCWNLr4SPV", popularity: 18.0 },
{ artist: "DeWayne Woods", spotifyID: "324RKHiPLIE9eDklXEVXce", popularity: 33.0 },
{ artist: "Nick Schnebelen", spotifyID: "6Zr9DBSIwtRuCEj0S0pcpz", popularity: 9.0 },
{ artist: "Frank Wess", spotifyID: "1yy6FH5FQX3RQqxnjMPRBn", popularity: 28.0 },
{ artist: "Lynda Randle", spotifyID: "5WWuo8k0komiDBmtec6gHI", popularity: 38.0 },
{ artist: "Kutt Calhoun", spotifyID: "78nL8LitGR7vO0qp2iZF9E", popularity: 44.0 },
{ artist: "Christopher Willits", spotifyID: "0XHtezS69NYZ51SEFh8WEA", popularity: 48.0 },
{ artist: "Chely Wright", spotifyID: "1aSIXmBKKrEVIbGLwhedIe", popularity: 38.0 },
{ artist: "Mac Lethal", spotifyID: "37xeUAohEFPICmvIRw4jil", popularity: 49.0 },
{ artist: "Marion Talley", spotifyID: "6bdykburN7FvBdRUn10IOo", popularity: 0.0 },
{ artist: "Big Scoob", spotifyID: "1PnsxAfjwnxNODAaKTu8VO", popularity: 47.0 },
{ artist: "Lester Young", spotifyID: "05E3NBxNMdnrPtxF9oraJm", popularity: 49.0 },
{ artist: "Tech N9ne", spotifyID: "6UBA15slIuadJ8h2lPRPos", popularity: 72.0 },
{ artist: "Ben Webster", spotifyID: "34W7ZCX0LZeJd8q6boKGOk", popularity: 52.0 },
{ artist: "Solé", spotifyID: "4NcMrSi3B8eUVy6e1Ni3wu", popularity: 47.0 },
{ artist: "Beautiful Bodies", spotifyID: "1L5Wcid8qi4K85Ynq7mLaZ", popularity: 27.0 },
{ artist: "Flee the Seen", spotifyID: "2LxdUCd3lVjL8lpTjEIuT0", popularity: 6.0 },
{ artist: "Bakers Pink", spotifyID: "7lqq60z0Rhg05Yvjw08lWM", popularity: 2.0 },
{ artist: "Downthesun", spotifyID: "4XoBA74crUS9HJMBUdfhjo", popularity: 17.0 },
{ artist: "The Casket Lottery", spotifyID: "3kSqc2brwAF1kWRFWYe2fW", popularity: 20.0 },
{ artist: "Ces Cru", spotifyID: "7jNpkZ55HFuYxJo6q1qawG", popularity: 48.0 },
{ artist: "Frost Like Ashes", spotifyID: "4GOyzrwfHpae8phPiz6oKu", popularity: 4.0 },
{ artist: "Axium", spotifyID: "1sLEpwxw6m9QboOcxk0IzJ", popularity: 0.0 },
{ artist: "Queens Club", spotifyID: "7mxgfq5JWOD2FAzm63of7f", popularity: 8.0 },
{ artist: "The Get Up Kids", spotifyID: "54Bjxn26WsjfslQbNVtSCm", popularity: 46.0 },
{ artist: "Architects", spotifyID: "3ZztVuWxHzNpl0THurTFCv", popularity: 63.0 },
{ artist: "The Republic Tigers", spotifyID: "2SWC5aiQJOx1BRIktgm354", popularity: 24.0 },
{ artist: "Reggie and the Full Effect", spotifyID: "5XURjhDMRoF4vrSAJj8vIN", popularity: 37.0 },
{ artist: "Antennas Up", spotifyID: "3ekyyPjYTszB7EQug8WhRu", popularity: 7.0 },
{ artist: "The Greeting Committee", spotifyID: "1MIe1z4RdqLqHSJsb7EBMm", popularity: 47.0 },
{ artist: "JPT Scare Band", spotifyID: "48g6ZfNgevSdnWtzrBLGnt", popularity: 5.0 },
{ artist: "The Gadjits", spotifyID: "4KsM4oeDrY0Akg6fGtvn1i", popularity: 18.0 },
{ artist: "The Coctails", spotifyID: "1bKgqsC8xWm1wgOQ8Gqs8z", popularity: 10.0 },
{ artist: "The Golden Republic", spotifyID: "4vnM612mTDlgCB5U4tlgCa", popularity: 1.0 },
{ artist: "Tango Lorca", spotifyID: "6ubBZIiD8FDrNHu9zEW8Rf", popularity: 3.0 },
{ artist: "Pomeroy", spotifyID: "49CsxCARbj3drTCCNdGzHs", popularity: 9.0 },
{ artist: "Making Movies", spotifyID: "1wFpAE8HCGoqaLjzRO51w9", popularity: 32.0 },
{ artist: "The Front", spotifyID: "5ictveRyhWRs8Gt8Dvt1hS", popularity: 61.0 },
{ artist: "Blue Riddim Band", spotifyID: "0SM1PAIZXYihMJPePoYqPR", popularity: 1.0 },
{ artist: "Heroes and Villains", spotifyID: "6gwCIoDWLOFGepuC089AHs", popularity: 0.0 },
{ artist: "Isaac James", spotifyID: "1s3FDSyA4BwD1Vsf9rOIGA", popularity: 1.0 },
{ artist: "Coalesce", spotifyID: "2T8rmKa2k1uot2okGULagY", popularity: 23.0 },
{ artist: "Hembree", spotifyID: "0NTqSkdyIji6DuHVac7ROJ", popularity: 39.0 },
{ artist: "Troglodyte", spotifyID: "6oW14gK1y7BR2HndbfNblS", popularity: 9.0 },
{ artist: "Shooting Star", spotifyID: "7xO0qIeS2GUpnI6nFz041C", popularity: 26.0 },
{ artist: "Season to Risk", spotifyID: "78B864EG41ixMzgvDgVNTA", popularity: 6.0 },
{ artist: "Suneaters", spotifyID: "2k6LNPlCMSftIQJXfsonin", popularity: 1.0 },
{ artist: "Madisen Ward and the Mama Bear", spotifyID: "5l3blxapQi6wu9e4V7BMon", popularity: 33.0 },
{ artist: "Shy Boys", spotifyID: "7hDw3suvKY0KLud00BuzHL", popularity: 24.0 },
{ artist: "The Life and Times", spotifyID: "7r9Mv6R4XgZLnCnbsMnhBX", popularity: 20.0 },
{ artist: "Puddle of Mudd", spotifyID: "3dXaa6jwM7B52GZpaJEIr5", popularity: 65.0 },
{ artist: "The Rainmakers", spotifyID: "1Yn0AutKzKDoa0rvPyCmSe", popularity: 25.0 },
{ artist: "Hearts of Darkness", spotifyID: "1jNH0CqorIFf7VUWyxKcDp", popularity: 0.0 },
{ artist: "Trampled Under Foot", spotifyID: "1IR09fnMJMFbwX7py3VHkY", popularity: 21.0 },
{ artist: "Boys Life", spotifyID: "6pkUxQmEvLkvQRa75wf7Ta", popularity: 12.0 },
{ artist: "Red Line Chemistry", spotifyID: "2hTFYVduEywDC8zUUUVbUE", popularity: 29.0 },
{ artist: "Vedera", spotifyID: "13s3CA5chKKPo7sXja8fLO", popularity: 16.0 },
{ artist: "Skatterman & Snug Brim", spotifyID: "18UXMAe8MYg68DcC7qynaT", popularity: 13.0 },
{ artist: "Lo-Key?", spotifyID: "1ehqyqdZUIBIQQP02i8Lmq", popularity: 37.0 },
{ artist: "Missouri", spotifyID: "6Y3ByR0evBqzxTHPkM2tX5", popularity: 22.0 },
{ artist: "Kansas City Chorale", spotifyID: "2QssUv03ph6oR7ltIfZUCZ", popularity: 20.0 },
{ artist: "The Elders", spotifyID: "1vV4PNRH6SBycDRxAz4YXt", popularity: 30.0 },
{ artist: "Shiner", spotifyID: "07Y8JgX0uHDWSBehZGncbg", popularity: 27.0 },
]

module.exports = kansasCityMOArtists;