[{ artist: "Tony Bellamy", spotifyID: "5pCZ54eQQ5izmSbaGe4ha2", popularity: 0.0 },
{ artist: "Ginger Costa-Jackson", spotifyID: "2Dlz4RB9oC9QeDzsQXD5eq", popularity: 0.0 },
{ artist: "Dave Fogg", spotifyID: "0XvB7SU7OSAsJivqU50IIY", popularity: 2.0 },
{ artist: "Ben McKee", spotifyID: "4Nr8r2DYhxdi2nwehrwxRw", popularity: 2.0 },
{ artist: "3LAU", spotifyID: "4YLQaW1UU3mrVetC8gNkg5", popularity: 64.0 },
{ artist: "Brent Fitz", spotifyID: "2E9IBymoAVDGQ3PifNY7eS", popularity: 4.0 },
{ artist: "Joshua Alan", spotifyID: "6UfALKgvP9gwasPjcIqM3p", popularity: 0.0 },
{ artist: "JGivens", spotifyID: "1Xq1gv1FyECCWgSyTP0dN3", popularity: 36.0 },
{ artist: "Tim Mooney", spotifyID: "0X03x3QTW5ZbJJdomuDLCF", popularity: 0.0 },
{ artist: "Sandra Collins", spotifyID: "1Wkm5Jz5ZmVSE4idjPOfJp", popularity: 11.0 },
{ artist: "JR Castro", spotifyID: "19xmzzjYSHNrV6s0DBzEi7", popularity: 35.0 },
{ artist: "Nikki Holland", spotifyID: "1A63WHpYjdcSgCOwcuc71p", popularity: 0.0 },
{ artist: "ZaZa Maree", spotifyID: "4CltKnDusvqlkRhuVBlzOE", popularity: 17.0 },
{ artist: "Harold Geller", spotifyID: "7LEx3aEIxsETSXt5e98Xmq", popularity: 1.0 },
{ artist: "Leah Dizon", spotifyID: "24XmBORlPSAkYX6QKRDgti", popularity: 12.0 },
{ artist: "Nick Oshiro", spotifyID: "661tIJNAvxietORrv0i2s2", popularity: 0.0 },
{ artist: "Frank Sinatra Jr.", spotifyID: "5fElZYhQFp0lEc4FQVcRu1", popularity: 29.0 },
{ artist: "Wayne Sermon", spotifyID: "4YYjnQ3wByJsGQczDYIY1q", popularity: 14.0 },
{ artist: "Mikalah Gordon", spotifyID: "4nrIaLSoQt44gzQRHVP9EN", popularity: 0.0 },
{ artist: "Social Repose", spotifyID: "2KGgkFhzF8mQwDy321OHIy", popularity: 39.0 },
{ artist: "Barbara Robison", spotifyID: "0GrKpNK3TelIfUdeRzaMvx", popularity: 12.0 },
{ artist: "Carl Fontana", spotifyID: "2JGM5oFaAn9Qc3eLHwcjes", popularity: 15.0 },
{ artist: "RiceGum", spotifyID: "5RQqbE8uh2NwotXk6wvYa6", popularity: 48.0 },
{ artist: "Mark Stoermer", spotifyID: "0xoQth0DUaauLf3A5sNveW", popularity: 20.0 },
{ artist: "Elvis Presley", spotifyID: "43ZHCT0cAZBISjO8DG9PnE", popularity: 79.0 },
{ artist: "Jim Root", spotifyID: "2QdlvDLgD7FDA6ayhGv95R", popularity: 5.0 },
{ artist: "Aja Volkman", spotifyID: "1acEKKXSDIHJifhq0Bj3g1", popularity: 39.0 },
{ artist: "Monte Money", spotifyID: "4hasGqJvaO0rna1x8jg3D5", popularity: 7.0 },
{ artist: "Dizzy Wright", spotifyID: "1LrWZc2qPhRCHyr6XtpBxq", popularity: 61.0 },
{ artist: "David Yow", spotifyID: "4OHQ5ZiLr2huATcz5g5988", popularity: 1.0 },
{ artist: "Wayne Newton", spotifyID: "5NX29TmuYrENlpvz6IgYMJ", popularity: 44.0 },
{ artist: "Daniel Platzman", spotifyID: "4wJ6sdRcUngdmBXjvMJyO6", popularity: 21.0 },
{ artist: "Violetta Villas", spotifyID: "5LkBYcUF2oRDRDwyuu9rlf", popularity: 22.0 },
{ artist: "Toney Rocks", spotifyID: "603ctQbXdODw13dMIpfyd0", popularity: 0.0 },
{ artist: "Ben Stivers", spotifyID: "6m4yKZ7YNrCgCP4OT9GIaU", popularity: 0.0 },
{ artist: "Jeremy Spencer", spotifyID: "46HOAQwa7E78qYJ0SHCg6o", popularity: 25.0 },
{ artist: "Sergio Franchi", spotifyID: "3afJ7ksCTA53PwM233jIf8", popularity: 23.0 },
{ artist: "Dan Reynolds", spotifyID: "3k3gbUT7bF0jYmFmAKBQtU", popularity: 36.0 },
{ artist: "James Moody", spotifyID: "4aEpM8RuVFDhH7ry8TUn4M", popularity: 29.0 },
{ artist: "Big B", spotifyID: "0dwYOqqBADcpYOJRmlZSgH", popularity: 41.0 },
{ artist: "Paul Taylor", spotifyID: "3wBSOZFd5KLsEZ1yoVSICQ", popularity: 42.0 },
]