[{ artist: "George Balch Wilson", spotifyID: "7y1MmNCfNgHrePlWZXkyA1", popularity: 0.0 },
{ artist: "Max Crook", spotifyID: "0KClUSWvzT3BQyRjnoDMeM", popularity: 0.0 },
{ artist: "Boxcar Willie", spotifyID: "6ISSzeT1ACKbGLO0JBZ23r", popularity: 30.0 },
{ artist: "Matthew Sweet", spotifyID: "2idymNTKUdnTxforkb12Mw", popularity: 44.0 },
{ artist: "Lucille Norman", spotifyID: "1G1LrBhPQt2PP1vam477nx", popularity: 0.0 },
{ artist: "Lauren Ward", spotifyID: "6RFGwX2bAZqXSeXfdqzXUY", popularity: 38.0 },
{ artist: "Gordon MacRae", spotifyID: "3dvIPsJH7o9xnBwFxowzof", popularity: 35.0 },
{ artist: "Mike Mennard", spotifyID: "4yDpgi0yvqiLa0rBKgTenG", popularity: 10.0 },
{ artist: "BryanStars", spotifyID: "5v3g0atgbassIF35BXGvxi", popularity: 14.0 },
{ artist: "David Garner", spotifyID: "37FILWCsfS0RoxWKLYl5kG", popularity: 13.0 },
{ artist: "Jon Peter Lewis", spotifyID: "1HBwEZcehyEx0JU8jmvkc5", popularity: 10.0 },
{ artist: "Nathaniel Motte", spotifyID: "3wRzP7eplylJi1s7byCJKq", popularity: 3.0 },
{ artist: "Joshua James", spotifyID: "0YLUOdFiedWIWBttlDAQeO", popularity: 44.0 },
{ artist: "James Valentine", spotifyID: "3oVy8P94MScKFNSMGaYWeA", popularity: 14.0 },
{ artist: "John Moran", spotifyID: "2DYUqITyiQa3vdquZzAtZp", popularity: 11.0 },
{ artist: "The Millions", spotifyID: "4bCXgLyFqKJwz5x9o0U9ZG", popularity: 3.0 },
]