const newArkNJArtists = [{ artist: "Vivian Blaine", spotifyID: "6NvuGN3n9Ygub10wEQo7al", popularity: 10.0 },
{ artist: "Vinnie Burke", spotifyID: "2f7E2frr4rryAgkKN6xmMm", popularity: 0.0 },
{ artist: "Dez Cadena", spotifyID: "7hYVVQtW4xyPd6GrFO0ral", popularity: 15.0 },
{ artist: "Akon", spotifyID: "0z4gvV4rjIZ9wHck67ucSV", popularity: 79.0 },
{ artist: "William Boyle", spotifyID: "6XiHSCHdUwOD4u1tQU7F6H", popularity: 1.0 },
{ artist: "L. Russell Brown", spotifyID: "5hPbKZUnoxj6Ohzhbk6ahJ", popularity: 2.0 },
{ artist: "Tisha Campbell-Martin", spotifyID: "6mx0D9tlGW7OCTlrgDKaxs", popularity: 26.0 },
{ artist: "Salome Bey", spotifyID: "3Att8PWCMBdMkcdcUgNo0N", popularity: 0.0 },
{ artist: "Madeline Bell", spotifyID: "3Eiku2RFtR4xvfYi9kNO4D", popularity: 15.0 },
{ artist: "Bob Crewe", spotifyID: "2hDUxXgWCMrkwhaw5aG9U1", popularity: 14.0 },
{ artist: "Connie Francis", spotifyID: "3EY5DxGdy7x4GelivOjS2Q", popularity: 55.0 },
{ artist: "Tommy DeVito", spotifyID: "2fsFpOUzCc2W1oVPLxydqb", popularity: 0.0 },
{ artist: "Seymour Bernstein", spotifyID: "0iqgP6nKEVRnn6BKVT17kq", popularity: 2.0 },
{ artist: "Lou Brutus", spotifyID: "4m4LaJI6u83t0XnOU7NMCs", popularity: 0.0 },
{ artist: "Louis Coerne", spotifyID: "7t8gpibZPN9R65MIZ0Fhxk", popularity: 0.0 },
{ artist: "Faye Adams", spotifyID: "1bx4W3T0zPKzmsrRTvquWV", popularity: 25.0 },
{ artist: "David Conley", spotifyID: "1YIcYn1WW678icNcjKxYWy", popularity: 6.0 },
{ artist: "Bill Chinnock", spotifyID: "4gl3qjGVkweASR3WvcO7Wv", popularity: 5.0 },
{ artist: "Ann Cole", spotifyID: "1Ig4eJhkfzDB2386DVJ0TQ", popularity: 11.0 },
{ artist: "Larry Fast", spotifyID: "2TxykrNIaQV8U99krRJHG9", popularity: 15.0 },
{ artist: "Elisabeth Carron", spotifyID: "5GmOGAsvN6zJRzaAd5X6sC", popularity: 0.0 },
{ artist: "Gloria Gaynor", spotifyID: "6V6WCgi7waF55bJmylC4H5", popularity: 65.0 },
{ artist: "Charles Calello", spotifyID: "0k4DCtvm6yFj8OnuVKebTw", popularity: 0.0 },
{ artist: "James Cohn", spotifyID: "6vCfYZhHWmQtrKW3MjCG4K", popularity: 0.0 },
{ artist: "Mia Cox", spotifyID: "6x6c4i2B4AFPnGkvfo5iFi", popularity: 1.0 },
{ artist: "Erskine Butterfield", spotifyID: "60BPqCs86lKzFDY8qXkCxF", popularity: 0.0 },
{ artist: "LaShawn Daniels", spotifyID: "7GP86j2K8q8FB75yzRw3oX", popularity: 9.0 },
{ artist: "John Gorka", spotifyID: "2MWKhzU2iggdtLs4xLTqrP", popularity: 30.0 },
{ artist: "Alvin Darling", spotifyID: "52svBMBr5WlF5aKI4RQTaL", popularity: 18.0 },
{ artist: "Faith Evans", spotifyID: "5NDMothbpdpq2xHqSjrrWn", popularity: 67.0 },
{ artist: "Dolly Dawn", spotifyID: "2vJuZhw1vI5WDW6aZPwYl0", popularity: 12.0 },
{ artist: "David Fiuczynski", spotifyID: "3G0YsucT1VomRUB44ZV4gz", popularity: 13.0 },
{ artist: "Kat DeLuna", spotifyID: "0bOlhT8OcoC1lCpN69NcFP", popularity: 53.0 },
{ artist: "Vincent Herbert", spotifyID: "1u6mFzAwFf3HkzCADW9Ee7", popularity: 5.0 },
{ artist: "Andy Bey", spotifyID: "6nnjKHTxPpJtw08NqB0gvJ", popularity: 32.0 },
{ artist: "Eddie Gladden", spotifyID: "5udT4Shz5x5taZgQJsgW9z", popularity: 5.0 },
{ artist: "Scott LaFaro", spotifyID: "4g7uUySyORXh2KgDEhgxXa", popularity: 47.0 },
{ artist: "Eddie Drennon", spotifyID: "5cCnOTvuh6xlWf1ZA4trF2", popularity: 7.0 },
{ artist: "Julie Lyonn Lieberman", spotifyID: "6Fje9V5wlCuyTDKrOZhHON", popularity: 0.0 },
{ artist: "Taana Gardner", spotifyID: "4kkfqDFX2t4QBOwuHqAROF", popularity: 28.0 },
{ artist: "Don Goldie", spotifyID: "6IuNDxs0zYT63cim1jpzfR", popularity: 3.0 },
{ artist: "Nancey Jackson Johnson", spotifyID: "34HYpG61Tdys6LKZGia9LO", popularity: 2.0 },
{ artist: "Maria Jeritza", spotifyID: "4UKmsqTsatj9cSgPvw4g9W", popularity: 0.0 },
{ artist: "Leroy Hutson", spotifyID: "5YJjMGHVQj1IHBabXX8lH6", popularity: 42.0 },
{ artist: "Bill Finegan", spotifyID: "08E0lmgmD5w6kKthQFHyG5", popularity: 0.0 },
{ artist: "Carl Kress", spotifyID: "0KL26rUVFAqUcfnXbJRksT", popularity: 12.0 },
{ artist: "Richard Himber", spotifyID: "3Rj3lY5R1BIFD3527AlLSN", popularity: 19.0 },
{ artist: "Charlie Nothing", spotifyID: "0DyNbMlY53Gpwj7Tik373X", popularity: 0.0 },
{ artist: "Bernard Greenhouse", spotifyID: "33m8hHvylEDLzWwVkCgnPg", popularity: 17.0 },
{ artist: "Henry Holden Huss", spotifyID: "1792cHn9J6JtEL0ACbkUN4", popularity: 0.0 },
{ artist: "Nil Lara", spotifyID: "2GsEm24OcYd7Qldt8bAHeZ", popularity: 24.0 },
{ artist: "Barry Miles", spotifyID: "1Cy6swbBmTbhfL00cEc7IC", popularity: 6.0 },
{ artist: "Marc Ribot", spotifyID: "7jAeRfT8LYCxydM2Y1Egvn", popularity: 38.0 },
{ artist: "Gary Lewis", spotifyID: "0XTxadWXVyfB8eTIYOjMYj", popularity: 41.0 },
{ artist: "Grachan Moncur III", spotifyID: "5NrnFpBCv4Z43MgMVXfrrY", popularity: 12.0 },
{ artist: "Nick Lucas", spotifyID: "0QMxshFmGwF4vcedM4pHEw", popularity: 16.0 },
{ artist: "Jerome Kern", spotifyID: "09E7wcrEyqU2n1rnhzVT0h", popularity: 31.0 },
{ artist: "Raheem DeVaughn", spotifyID: "59NO6KX7wQCG7jGdtH1NtL", popularity: 53.0 },
{ artist: "Antoinette Montague", spotifyID: "3sIU7h22WOoYvGCaC8dhy4", popularity: 0.0 },
{ artist: "Mark Radice", spotifyID: "0b3wwjk827soh6Elb1DBvt", popularity: 0.0 },
{ artist: "Frankie Negrón", spotifyID: "3QPEwHBLL8xX8p8HaT4S16", popularity: 39.0 },
{ artist: "Willie Jae", spotifyID: "4bu8AR8OG5EK7ZgtSvsJbG", popularity: 0.0 },
{ artist: "Derek Lee Ragin", spotifyID: "6LHrQNiImZwR2we4oxMtlK", popularity: 31.0 },
{ artist: "Charlie Persip", spotifyID: "3VyI0eQoAAeXJQZAsq1lth", popularity: 12.0 },
{ artist: "Jerry Lewis", spotifyID: "2zyz0VJqrDXeFDIyrfVXSo", popularity: 58.0 },
{ artist: "Max Pollikoff", spotifyID: "6CBSHwxdmLYsphWnYDMfjM", popularity: 0.0 },
{ artist: "Joe Pesci", spotifyID: "0lw0ffS7QCtXnDD2uNAxGQ", popularity: 17.0 },
{ artist: "Okieriete Onaodowan", spotifyID: "6G3sPhnj4JBCsBVBGvZnkk", popularity: 68.0 },
{ artist: "Houston Person", spotifyID: "16Xx0WCnAKOA9mwPPSUJmr", popularity: 33.0 },
{ artist: "James Lyon", spotifyID: "0qZbzCm6hWIVvVCtPCdAYN", popularity: 0.0 },
{ artist: "Cissy Houston", spotifyID: "4QYDxx5VDqINxMtUapyF9q", popularity: 34.0 },
{ artist: "James Moody", spotifyID: "4aEpM8RuVFDhH7ry8TUn4M", popularity: 28.0 },
{ artist: "Melba Moore", spotifyID: "0uMy5ZKVPBHauBYTTfCojq", popularity: 43.0 },
{ artist: "Paul Phillips", spotifyID: "0XKmkd2McuYjaPuFqzt67J", popularity: 16.0 },
{ artist: "Rob Paparozzi", spotifyID: "5zGWplWhoDJAVRwGKpAZBq", popularity: 0.0 },
{ artist: "Donald Malloy", spotifyID: "4g35eV13YofKYWho1D7zYh", popularity: 10.0 },
{ artist: "Jim Pugliese", spotifyID: "0pWvBTwWnGV27uMvcyZ5UY", popularity: 0.0 },
{ artist: "Latrelle", spotifyID: "2mUoO8KgRQOOzR0VoUWoEV", popularity: 3.0 },
{ artist: "Jeff Banks", spotifyID: "6f4J8LXvuUnYbeRluPmPvu", popularity: 5.0 },
{ artist: "Dick Charles", spotifyID: "3kpWXkjdmzRUwbaffzcKOw", popularity: 0.0 },
{ artist: "Stefanie Minatee", spotifyID: "1IlNmLB2vGeUizNoBM2bjp", popularity: 0.0 },
{ artist: "Marie Knight", spotifyID: "5SQDx1d1tEpptg9je4XGYS", popularity: 11.0 },
{ artist: "Linda Jones", spotifyID: "7erYZsfekXYGWvup1bnkUZ", popularity: 32.0 },
{ artist: "Pat Senatore", spotifyID: "4r6mwtaNARbTHv5Nk0FXvj", popularity: 14.0 },
{ artist: "Wayne Shorter", spotifyID: "0ZqhrTXYPA9DZR527ZnFdO", popularity: 50.0 },
{ artist: "Bilal Salaam", spotifyID: "1NO93CD1MfWbv1hMKUfEOo", popularity: 24.0 },
{ artist: "Steve Swell", spotifyID: "63mW3Dk3IOcppvvV3R5Hlo", popularity: 7.0 },
{ artist: "David Schnitter", spotifyID: "3svp7inpZAgntFvHG3lZz0", popularity: 0.0 },
{ artist: "Terry Silverlight", spotifyID: "3iUSWFz8DkxL2DhrdOH2im", popularity: 2.0 },
{ artist: "Harry Simeone", spotifyID: "30orN5PtRhj9fN2Myr8HKV", popularity: 26.0 },
{ artist: "Steve Scott", spotifyID: "1qVQrXeIkr1syniSeN5XKA", popularity: 0.0 },
{ artist: "Buddy Terry", spotifyID: "2O2g4eCsOjDNNpLhlsJFNK", popularity: 4.0 },
{ artist: "Tyshawn Sorey", spotifyID: "0j2falzYTCLSgKpGKQipQu", popularity: 12.0 },
{ artist: "Michael Tree", spotifyID: "1XkbOCJKFyZu8XRxjqhblt", popularity: 11.0 },
{ artist: "DJ Symphony", spotifyID: "75nXQyLeB5YjzE7LV8l5gx", popularity: 0.0 },
{ artist: "Frankie Valli", spotifyID: "6mcrZQmgzFGRWf7C0SObou", popularity: 65.0 },
{ artist: "Brittany Underwood", spotifyID: "7ny6T4Ldm55AVoEfB4J6rQ", popularity: 5.0 },
{ artist: "Morton Stevens", spotifyID: "0RDdPCcAkdDxiRCNJbBlK0", popularity: 17.0 },
{ artist: "Marc Shaiman", spotifyID: "4A5NGno1SttXk4vB4SLGHo", popularity: 46.0 },
{ artist: "Ahsan Watts", spotifyID: "0vYr3HfrbRC1koZRgwtFQ5", popularity: 0.0 },
{ artist: "Carrie Smith", spotifyID: "65gGZ8AfbxuEGx62bd8WVP", popularity: 12.0 },
{ artist: "Woody Shaw", spotifyID: "0yvEf1tqWWPiZu4ZbjyKGs", popularity: 34.0 },
{ artist: "Junior Sanchez", spotifyID: "31ZNfGVEEcI9CyicPVJQni", popularity: 49.0 },
{ artist: "Larry Young", spotifyID: "6Y6kAZs0W9NNsxNbpImPvq", popularity: 28.0 },
{ artist: "Marty Sheller", spotifyID: "0K4T73EIF6gnwWwWlqXAFo", popularity: 0.0 },
{ artist: "Wyclef Jean", spotifyID: "7aBzpmFXB4WWpPl2F7RjBe", popularity: 71.0 },
{ artist: "Max Weinberg", spotifyID: "2CQR7qxQyuF1Ak86bKdn4T", popularity: 5.0 },
{ artist: "Grady Thomas", spotifyID: "3TxP9mL0xk23GkHkMfYzhG", popularity: 0.0 },
{ artist: "Internal Quest", spotifyID: "5i1LvPPKJPoBTSk0i8gRrD", popularity: 15.0 },
{ artist: "Dee Dee Warwick", spotifyID: "3KeTziLAcJFEnbhfIMRh5w", popularity: 26.0 },
{ artist: "Larry Weiss", spotifyID: "3F1K7HEN17beHEBfHmbg2I", popularity: 19.0 },
{ artist: "Datin", spotifyID: "2ZNeZlHauwGYZ9XADyjSL4", popularity: 36.0 },
{ artist: "Ho99o9", spotifyID: "5KuuNGYTUTokLerXMNYCGL", popularity: 46.0 },
{ artist: "Jimmie Smith", spotifyID: "3bAYWocozEfyAvjkvjbWvf", popularity: 3.0 },
{ artist: "Driicky Graham", spotifyID: "7h5oEr0hzlM0GFQMrgEwSo", popularity: 30.0 },
{ artist: "Julissa Veloz", spotifyID: "5yUaYt1kK0MjwlOXAcYgNF", popularity: 7.0 },
{ artist: "Zakiya", spotifyID: "124AxXBDIQi7Ko1LGI6eUj", popularity: 2.0 },
{ artist: "El Da Sensei", spotifyID: "1MdXFbsQnABjfzSxlJLzRB", popularity: 29.0 },
{ artist: "Rah Digga", spotifyID: "1uT0jnwsq3AifrLorG4UDt", popularity: 43.0 },
{ artist: "Natalie Wilson", spotifyID: "30Bj8VKaPPWSctZs3KwP0g", popularity: 7.0 },
{ artist: "Ice-T", spotifyID: "0eGh2jSWPBX5GuqIHoZJZG", popularity: 50.0 },
{ artist: "Queen Latifah", spotifyID: "5m7wCUhYhBh7A3A3YMxrbt", popularity: 58.0 },
{ artist: "Paul Simon", spotifyID: "2CvCyf1gEVhI0mX6aFXmVI", popularity: 71.0 },
{ artist: "Sarah Vaughan", spotifyID: "1bgyxtWjZwA5PQlDsvs9b8", popularity: 55.0 },
{ artist: "Samuel A. Ward", spotifyID: "0DlVk18MAbEqGfTUzoVK41", popularity: 19.0 },
{ artist: "Artifacts", spotifyID: "4hz8ohK9ESaFbJBAXvWJGL", popularity: 49.0 },
{ artist: "Lords of the Underground", spotifyID: "17Q9sCBpIyS6yM2YyaI6R4", popularity: 50.0 },
{ artist: "Neako", spotifyID: "4l8WPB3dhjAUOFcoCa8FOR", popularity: 29.0 },
{ artist: "Tame One", spotifyID: "1EoI42jrKtZiXtti5YormP", popularity: 23.0 },
{ artist: "Roger \"Hurricane\" Wilson", spotifyID: "1q43mfq0oVe4S3GzIePE8W", popularity: 1.0 },
{ artist: "Redman", spotifyID: "7xTKLpo7UCzXSnlH7fOIoM", popularity: 67.0 },
{ artist: "Fred Schneider", spotifyID: "7HWVWTbgJBXqBX6Jd4AvzJ", popularity: 16.0 },
]

module.exports = newArkNJArtists;