[{ artist: "Henry Doktorski", spotifyID: "1F6tn0wn0PbbWDM3UWAKML", popularity: 1.0 },
{ artist: "Franke Previte", spotifyID: "3GzfDAzRuvCPjye4hQsKLF", popularity: 0.0 },
{ artist: "Hoagy Lands", spotifyID: "6ad1aRY4ao85Etnv3e79YT", popularity: 0.0 },
{ artist: "Mark Helias", spotifyID: "477gMnSsaTHsAIDlidg1Ra", popularity: 6.0 },
{ artist: "Gil Morgenstern", spotifyID: "0mgULXtyOENNH8iNVO9HJe", popularity: 0.0 },
{ artist: "Jonathan Leshnoff", spotifyID: "3Ly5zjk1yiWZDaxMpfDoiR", popularity: 10.0 },
{ artist: "Edythe Wright", spotifyID: "0J1JUJMr6AmojUgUie8kY1", popularity: 16.0 },
{ artist: "I.O.U.", spotifyID: "50d0RaF48XKM5MginCWn40", popularity: 5.0 },
{ artist: "The Gaslight Anthem", spotifyID: "7If8DXZN7mlGdQkLE2FaMo", popularity: 56.0 },
{ artist: "Jaheim", spotifyID: "4sbB4Yy6Qig51pKCIKSLw3", popularity: 57.0 },
{ artist: "Rick Seibold", spotifyID: "6XoVFoAjQoFlgTL7ZzOQK7", popularity: 1.0 },
{ artist: "Carol Connors", spotifyID: "2oUH0TmQIBQDFpIFmG14bf", popularity: 8.0 },
{ artist: "David Kikoski", spotifyID: "11c9fr8DFDGQZ1Cv77L8PW", popularity: 18.0 },
{ artist: "PJ Bond", spotifyID: "6ili686Xi9HQdOAFOGPam8", popularity: 4.0 },
{ artist: "James P. Johnson", spotifyID: "0BMlIte9CqjItQ6mh2GoGi", popularity: 23.0 },
{ artist: "Lance Carter", spotifyID: "03cQ1wt3ARTYNkzdxPprdB", popularity: 0.0 },
{ artist: "Streetlight Manifesto", spotifyID: "1OKOTYGoCE2buxTYMegJp7", popularity: 55.0 },
{ artist: "Gates", spotifyID: "1gPhS1zisyXr5dHTYZyiMe", popularity: 78.0 },
]