const newRochelleNYArtists = [{ artist: "Bob Coltman", spotifyID: "0qiS76B3p95WIhYPCYD6el", popularity: 0.0 },
{ artist: "Derek Bermel", spotifyID: "57vCdaiX5bF2PZc04XHUQT", popularity: 6.0 },
{ artist: "Jan Peerce", spotifyID: "5JzVslhlp7wvDdVgynlN16", popularity: 16.0 },
{ artist: "Claude Thornhill", spotifyID: "6ThTN0WCRCAtG00Htf7CUW", popularity: 18.0 },
{ artist: "Don McLean", spotifyID: "1gRNBaI4yn6wCCTvRhGWh8", popularity: 66.0 },
{ artist: "Graham Clarke", spotifyID: "4NfGBQOxL1A1yUG7xTDFHo", popularity: 1.0 },
{ artist: "Marlena Shaw", spotifyID: "0hirZ8kPPdM9pzXpoagB4w", popularity: 51.0 },
{ artist: "Alan Menken", spotifyID: "5sy77gt4bfsLcSQ8GIe4ZZ", popularity: 65.0 },
{ artist: "Willie Colón", spotifyID: "7x5Slu7yTE5icZjNsc3OzW", popularity: 68.0 },
{ artist: "Joan Tower", spotifyID: "5506BdXZgoHhWIZtWEGynH", popularity: 11.0 },
{ artist: "Del James", spotifyID: "4nVhF8BxG37lBqyX4Ef8SN", popularity: 0.0 },
{ artist: "Bob Mintzer", spotifyID: "2yKX1WpgVIxOJbwBbFwqQ0", popularity: 29.0 },
{ artist: "John Frederick Coots", spotifyID: "1GBWQ6k6wcK04Uhk3arz5b", popularity: 2.0 },
{ artist: "Daniel Dorff", spotifyID: "5isL2P7iz7E4NP68HWEByG", popularity: 1.0 },
{ artist: "Horace Silver", spotifyID: "5ZATfKurLqflrBhv2FLht5", popularity: 49.0 },
{ artist: "George Treadwell", spotifyID: "5InyauVwWG3pPmXZfxOE0h", popularity: 0.0 },
{ artist: "David Schiff", spotifyID: "6RlFxY6bpcSdtpCK9hd3Rw", popularity: 0.0 },
{ artist: "Scram Jones", spotifyID: "0Bi7gsMOc5xrBd3gSfGsFZ", popularity: 24.0 },
{ artist: "Renata Scotto", spotifyID: "5W7pOtn53qBRrQo00IvHTj", popularity: 37.0 },
{ artist: "Jordan McLean", spotifyID: "4dPWyxZj7bNtGlkyjrJKOX", popularity: 11.0 },
{ artist: "CL Smooth", spotifyID: "3fJ60AcIgLzQkVitEvA7uq", popularity: 52.0 },
{ artist: "Susan Metcalfe Casals", spotifyID: "0g9DiNtSyZx5fTIoYuwIjj", popularity: 0.0 },
{ artist: "David Starobin", spotifyID: "5B49fd5IP74BVYaAzI7X9I", popularity: 22.0 },
{ artist: "Della Griffin", spotifyID: "1F3HpaHAeJjbb8OIHupFzb", popularity: 3.0 },
{ artist: "Mary Healy", spotifyID: "44OYOTkCBgZFzKMUAASO3b", popularity: 0.0 },
{ artist: "Teresa Brewer", spotifyID: "2mPL4g4v9DS55zi6QctLbP", popularity: 32.0 },
{ artist: "Steve Ross", spotifyID: "0oIJRgNU67b9AseaWzxZs9", popularity: 15.0 },
{ artist: "Kara DioGuardi", spotifyID: "1j7YzIePqi8c7G0kVZe3nC", popularity: 12.0 },
{ artist: "Jerry Bilik", spotifyID: "0SMbioWCHSUbyzeSoF2FQM", popularity: 0.0 },
{ artist: "Ruth Schönthal", spotifyID: "1PPds3MUHoQMMKb47Ldv88", popularity: 0.0 },
{ artist: "Joey Calderazzo", spotifyID: "7wu4u8r54ZgGyY9FOZtDq4", popularity: 32.0 },
{ artist: "Peter DeRose", spotifyID: "4oMECXBvxGUNdwkgBLZvSR", popularity: 1.0 },
{ artist: "Guy Davis", spotifyID: "6PdVgi27EMfFXV5lSH6wEW", popularity: 29.0 },
{ artist: "Jerry Bock", spotifyID: "5if6qdSkweSBwhdvFfKbcC", popularity: 26.0 },
{ artist: "Branford Marsalis", spotifyID: "795yvukGj0UOfcP8uftDq9", popularity: 44.0 },
{ artist: "Susan Larson", spotifyID: "5HD2YnE9H5AzOvSaYYCES1", popularity: 0.0 },
{ artist: "Robert Merrill", spotifyID: "1G4jpiUOb1RmRNuaUhv1Ys", popularity: 29.0 },
{ artist: "Janet Maguire", spotifyID: "1u4FMgR0SfPlI2XwpuwCzY", popularity: 0.0 },
{ artist: "Grand Puba", spotifyID: "6IjhOxJSTPh15KgFTSZ68K", popularity: 49.0 },
{ artist: "Brad Kane", spotifyID: "3dAzSJ9lQnJSq5Z0OgDBep", popularity: 60.0 },
{ artist: "Lord Jamar", spotifyID: "2WSnJlJ0uGTjye4jGSN1GG", popularity: 25.0 },
{ artist: "Roy Hamilton", spotifyID: "03heaC5xiTnpquwHyHXr2s", popularity: 32.0 },
{ artist: "Robert Allen", spotifyID: "7xD9x4lsRnSjtfpUztjmFF", popularity: 16.0 },
{ artist: "Paul Whiteman", spotifyID: "0tIS1GWwrWqr4DHK0RLg5u", popularity: 27.0 },
{ artist: "David Tanenbaum", spotifyID: "1GtK9rOQJok6hwWNl9iiEi", popularity: 12.0 },
]

module.exports = newRochelleNYArtists;