const omahaNEArtists = [{ artist: "Kianna Alarid", spotifyID: "3ymLZfMyndgHhoPC00ORvN", popularity: 24.0 },
{ artist: "Ryan Fox", spotifyID: "38y247P7uwzEKagxEQ1uPG", popularity: 0.0 },
{ artist: "Todd Fink", spotifyID: "7Iqf401AaWeOy2B3G1NTCL", popularity: 2.0 },
{ artist: "Peter Buffett", spotifyID: "5OYsEzWYxTyO2pKSQxywcb", popularity: 18.0 },
{ artist: "Bryan Greenberg", spotifyID: "2s7yDhxYxmB8aq5Skh3oTG", popularity: 22.0 },
{ artist: "Steve Alaimo", spotifyID: "3mnvGu4mOJr5MVVPtvaZo6", popularity: 8.0 },
{ artist: "Matt Bowen", spotifyID: "7bnnviPNRdPBnDqoKrCyPA", popularity: 10.0 },
{ artist: "Sarah Benck", spotifyID: "4PM2KOmaPJg7YtD8b9zyU6", popularity: 1.0 },
{ artist: "Lester Abrams", spotifyID: "6MEQo797sQ0ukZfy42i0Mu", popularity: 0.0 },
{ artist: "Mars Black", spotifyID: "184xpEPg9Gpn953e9riwF1", popularity: 0.0 },
{ artist: "Matt Focht", spotifyID: "3wMDzCF8NZtMU2QANUctY1", popularity: 0.0 },
{ artist: "Adele Astaire", spotifyID: "2oWMC3kNmou3AnwKHEpon9", popularity: 5.0 },
{ artist: "Bliss Blood", spotifyID: "7sjO8A8AEdMX1AVku9l6lW", popularity: 0.0 },
{ artist: "Marc Johnson", spotifyID: "3AT9157jK9F2gMSViMdRUH", popularity: 43.0 },
{ artist: "Max T. Barnes", spotifyID: "6p0EnWxfmHnVrBdapvajJW", popularity: 10.0 },
{ artist: "Simon Joyner", spotifyID: "53PYmJ7bACIX8gkVoTkCIr", popularity: 20.0 },
{ artist: "Nick Hexum", spotifyID: "0lXQieFzHiPaeimBBGqAXY", popularity: 34.0 },
{ artist: "Tilky Jones", spotifyID: "4Sogh4R3vKoa3bmQnxBEdL", popularity: 8.0 },
{ artist: "Lloyd Hunter", spotifyID: "4qoLYsabY3w6AqNmz4xoBw", popularity: 0.0 },
{ artist: "Mike Donehey", spotifyID: "2jKlK6gsKyZDItyVP36II2", popularity: 23.0 },
{ artist: "Clark Baechle", spotifyID: "41m981rXecH6E7PxpWA0mM", popularity: 2.0 },
{ artist: "Wynonie Harris", spotifyID: "4Imc3wiT22cuynvQNpXcVn", popularity: 39.0 },
{ artist: "Morton Harvey", spotifyID: "3Btb0mDIvX9lftVNABU4Om", popularity: 5.0 },
{ artist: "Bernie Hanighen", spotifyID: "02vsGRGxxooTwYwSewH5Aa", popularity: 8.0 },
{ artist: "Matty Lewis", spotifyID: "185kaxyCCxQVMhDPOB8dsP", popularity: 33.0 },
{ artist: "Mike Freeman", spotifyID: "29MlqN3exMblwWLMVy8hbR", popularity: 8.0 },
{ artist: "Tim Kasher", spotifyID: "3e4qYL0Jd2HezQLZsCTqpN", popularity: 17.0 },
{ artist: "George Hamilton Green", spotifyID: "2JHa9xWsQOCeoLxd4adYpM", popularity: 6.0 },
{ artist: "Preston Love", spotifyID: "53iTFtcGxRuQw4jqktLyar", popularity: 12.0 },
{ artist: "Doug Ingle", spotifyID: "3cNcrU85cgBKfOKIQPoC3n", popularity: 0.0 },
{ artist: "Mandré", spotifyID: "4gp93oyCtmejjaduXV1IXG", popularity: 10.0 },
{ artist: "Thomas Wilkins", spotifyID: "1aZmBumib6BvFjHuICS5Sm", popularity: 1.0 },
{ artist: "Icky Blossoms", spotifyID: "3SlDsnTkmnKksYwO5HExTt", popularity: 24.0 },
{ artist: "Tim Halperin", spotifyID: "3nVeK8gQChVtVCCjGreal2", popularity: 49.0 },
{ artist: "Sean Keith", spotifyID: "0o5qo9QKStDBG1Ahfs92FK", popularity: 0.0 },
{ artist: "Burrill Phillips", spotifyID: "1zjBDWP7e8RRJY8ru89GdZ", popularity: 0.0 },
{ artist: "Linus of Hollywood", spotifyID: "5XslgFEsN0VWkiRWubk5ct", popularity: 12.0 },
{ artist: "Tim Wildsmith", spotifyID: "2dOBTMCtLB3oGbHnWpoVE3", popularity: 0.0 },
{ artist: "Ted Stevens", spotifyID: "4uoWBkhjKleZPmhPw68O7U", popularity: 0.0 },
{ artist: "Michael John Murphy", spotifyID: "0DKupv1DMxIhLvyEodfV2K", popularity: 0.0 },
{ artist: "Herbie Rich", spotifyID: "0mfmsebvoNSnignyLL7jzo", popularity: 0.0 },
{ artist: "Buddy Miles", spotifyID: "2E9nO9Zav9FjjlFVVtMWdw", popularity: 37.0 },
{ artist: "Dennis Mackrel", spotifyID: "3PUIxfK6P8boslOXGpZPoK", popularity: 8.0 },
{ artist: "Shaun Murphy", spotifyID: "1twaZYQvHBNn2eHbY4vc8m", popularity: 24.0 },
{ artist: "Fee Waybill", spotifyID: "5jdSkrjvDHTx5lS5FJSHQh", popularity: 18.0 },
{ artist: "Sparkle Moore", spotifyID: "4SPbyaeJhJ2vkRM61jsMYe", popularity: 6.0 },
{ artist: "John Lewis", spotifyID: "5WeqsLsgTxDKM3lulXjoPE", popularity: 38.0 },
{ artist: "Pigeon John", spotifyID: "3RfeWhoxAqlNRNcywG7RJj", popularity: 47.0 },
{ artist: "Conor Oberst", spotifyID: "2Z7gV3uEh1ckIaBzTUCE6R", popularity: 56.0 },
{ artist: "Paul Williams", spotifyID: "3f626JSVauIhTQgatsFcs4", popularity: 48.0 },
{ artist: "Jeri Southern", spotifyID: "53zwWZL3vLQ7fVfKrhrzaK", popularity: 27.0 },
{ artist: "Shirley Ross", spotifyID: "28u3S9uA2uefoRQuYZM222", popularity: 11.0 },
{ artist: "Jim Salestrom", spotifyID: "4hxxdfsHAgQgYNOyC9Akie", popularity: 0.0 },
{ artist: "Ann Ronell", spotifyID: "74IOFVn5V6L1z11WbeB9UW", popularity: 8.0 },
{ artist: "JoJo Siwa", spotifyID: "3Iq6waFNaQnjLjEjp2l3nc", popularity: 56.0 },
{ artist: "Thomas Morgan", spotifyID: "6txzCcsy6ZKKKQLHmE3Y9L", popularity: 40.0 },
{ artist: "Frank Reed", spotifyID: "2CXvBiL6K6wZtZ2plqf2Pe", popularity: 0.0 },
{ artist: "Richard Stoltzman", spotifyID: "26MvjOuSgBhoTW66u4WeMM", popularity: 29.0 },
{ artist: "Kris Tyler", spotifyID: "1XJTDKoQbVYmmRuo0cWNeH", popularity: 1.0 },
{ artist: "Billy Rich", spotifyID: "73NjnCPpQXzFY5AgA9xjqG", popularity: 0.0 },
{ artist: "Erik Turner", spotifyID: "3pI3yrpFSrZXFmr7LVdKfw", popularity: 15.0 },
{ artist: "Steve Turre", spotifyID: "1fJEAxQLhUQdBmUjsj3vIF", popularity: 22.0 },
{ artist: "Elliott Smith", spotifyID: "2ApaG60P4r0yhBoDCGD8YG", popularity: 62.0 },
]

module.exports = omahaNEArtists;