[{ artist: "Donald Fagen", spotifyID: "0S1SjYebdSaiMpI8xSW2Wb", popularity: 48.0 },
{ artist: "Tony Inzalaco", spotifyID: "19wVrujeKujLamvUypS7Eu", popularity: 0.0 },
{ artist: "Lewis Kaplan", spotifyID: "5PBtILS1lFFsLvWJGOg4mY", popularity: 0.0 },
{ artist: "Marvin David Levy", spotifyID: "5qZUfNqXONn9qfZFSa5137", popularity: 0.0 },
{ artist: "Frankie Randall", spotifyID: "6S4joQy9NymXyKyQFjg8Yp", popularity: 21.0 },
{ artist: "Ralph Rinzler", spotifyID: "6j3k1gFdx0MrJvKZfVieXM", popularity: 10.0 },
{ artist: "Peter Wilhousky", spotifyID: "5iA5RZI1NApzshkyUEUnaa", popularity: 12.0 },
{ artist: "Richie Ramone", spotifyID: "29zdX5JthMX1KYNwlYaoug", popularity: 12.0 },
{ artist: "Michael Zager", spotifyID: "1oX1l8zC13ovzEoGm2CAsd", popularity: 34.0 },
{ artist: "Bob Russell", spotifyID: "1zWet2PBkYJKgWQpWSlsEN", popularity: 17.0 },
{ artist: "Jack Fina", spotifyID: "36Jv930tZyxSpTJlHQALxO", popularity: 1.0 },
{ artist: "Robert Helps", spotifyID: "0PfjU7GDiilRc2c9yjIxYm", popularity: 3.0 },
]