[{ artist: "Pat DiNizio", spotifyID: "0M9n1PZNvicgGQby4zLbwQ", popularity: 3.0 },
{ artist: "Paul Crook", spotifyID: "4aVJSH0uVRq1NjgXM8qQhO", popularity: 13.0 },
{ artist: "Bill Evans", spotifyID: "4jXfFzeP66Zy67HM2mvIIF", popularity: 62.0 },
{ artist: "DJ Cheese", spotifyID: "5fUksOsRrC4Xv3LuNY8UZa", popularity: 0.0 },
{ artist: "Anthony Branker", spotifyID: "0VCgLs1q4XfvlCl4TQ8SG6", popularity: 0.0 },
{ artist: "Garry Shider", spotifyID: "74VW7C3P97VKA5euZfR6R8", popularity: 2.0 },
{ artist: "Florence LaRue", spotifyID: "647Sckg3HoLyl6CAcC40Pc", popularity: 0.0 },
{ artist: "Queena Mario", spotifyID: "3XTmhxjAdQAJSFg9AUvVFP", popularity: 0.0 },
{ artist: "Parliament-Funkadelic", spotifyID: "6XswoC68grx55in1WQnJ7E", popularity: 26.0 },
{ artist: "Cordell Mosson", spotifyID: "2OrKdiuOdCR0SCZPnWIw6T", popularity: 0.0 },
{ artist: "Betty Jones", spotifyID: "02Fb3REGxLjMofzm3tkXl1", popularity: 0.0 },
{ artist: "Dionne Farris", spotifyID: "7HO1DbzU86pWWp1vBN7l6k", popularity: 35.0 },
{ artist: "The Phantom Boyz", spotifyID: "55OqnUo1mmPJRfM6SiqT71", popularity: 2.0 },
{ artist: "Richard X. Heyman", spotifyID: "51EFYOtaNDDQdpLkkPImtf", popularity: 9.0 },
{ artist: "Nancy Van de Vate", spotifyID: "1YDURx3zYNPnoVXUpbsyUh", popularity: 1.0 },
{ artist: "Fred Van Eps", spotifyID: "0FGHUf0kHgnGAtRuEKH74b", popularity: 1.0 },
{ artist: "Dennis Báthory-Kitsz", spotifyID: "60O8RZPNhdmXxS1TAmwYy3", popularity: 0.0 },
{ artist: "Jeff Barry", spotifyID: "4h4nyO6EOTwCGe7LwwHR4I", popularity: 18.0 },
{ artist: "George Van Eps", spotifyID: "6QL3lIEWRff6Nn0Iy1yIps", popularity: 16.0 },
{ artist: "Donald Martino", spotifyID: "6ajViWQR5z9xTTu5RQUts6", popularity: 1.0 },
{ artist: "Billy Bass Nelson", spotifyID: "6EJOo4ApM2xiIkOGOGzvX4", popularity: 11.0 },
{ artist: "George Clinton", spotifyID: "2GVBp7QyHckoOg7rYkLvrA", popularity: 51.0 },
{ artist: "Bernie Worrell", spotifyID: "3vB7T6czx1Jh89YEnzM0UF", popularity: 29.0 },
{ artist: "David S. Ware", spotifyID: "53HPkfQRFqSSicbdJZuitU", popularity: 9.0 },
{ artist: "Vita", spotifyID: "4NEYQeEYBUjfaXgDQGvFvu", popularity: 70.0 },
]