[{artist:"Barton McLean",spotifyID:"1wZ6oYaAWo7HDU4MEYioC9",popularity:0.0},
{artist:"Alex Goot",spotifyID:"66Fb5gJ9SX2WGlqDLUpjux",popularity:55.0},
{artist:"Shawn Christensen",spotifyID:"45IA9QyYm1qXakVQWrRyx5",popularity:1.0},
{artist:"Adrianne Pieczonka",spotifyID:"0i7wTrA2VeXFoVT8AsEmIj",popularity:30.0},
{artist:"Happy Rhodes",spotifyID:"1JhNiTVtKV9LDUP5ljB6dK",popularity:14.0},
{artist:"Charles K. Harris",spotifyID:"5mf9xARniTBXZYxUctCJCT",popularity:1.0},
{artist:"Joseph Bertolozzi",spotifyID:"5hlvecPedlTWTsYStzIjYw",popularity:10.0},
{artist:"Keith Lockhart",spotifyID:"3xXehPffJ4rtaaCbqDwVJ3",popularity:31.0},
{artist:"Tao Rodríguez-Seeger",spotifyID:"2I1w4hO87kejWL0kXtlISy",popularity:8.0},
]