[{ artist: "Kevin Seconds", spotifyID: "65zOSzayAm0pvcI1sbsxp0", popularity: 13.0 },
{ artist: "Jeff Bernat", spotifyID: "2vVT4qoxWje0gVD2FiWZ4u", popularity: 60.0 },
{ artist: "Lorie Line", spotifyID: "3lk8qatIcUand38OeCGxk9", popularity: 25.0 },
{ artist: "Gavin Templeton", spotifyID: "63yxLcaTKQHR0vAKfIoYhc", popularity: 2.0 },
{ artist: "Willy Vlautin", spotifyID: "6HuUgtYC3JjDXGWuqXOJuS", popularity: 2.0 },
{ artist: "Ray Hackett", spotifyID: "5awIHlfWCWmbXiJjzT0g5G", popularity: 0.0 },
{ artist: "Carl Ravazza", spotifyID: "2uS01aaZj42WHhjv8UmbE9", popularity: 0.0 },
{ artist: "April Meservy", spotifyID: "2N0hvOQPfS4Kwi4ZLnSV6Z", popularity: 23.0 },
{ artist: "Chris Jones", spotifyID: "7hgMQaaF5Mzalln06NOvwa", popularity: 39.0 },
]