const rochesterNYArtists = [{ artist: "38 Spesh", spotifyID: "32cT1WQRSDg4xsReG7eqyT", popularity: 45.0 },
{ artist: "James Ferraro", spotifyID: "2gjrgz4DNYGrvQOpqLr2nv", popularity: 30.0 },
{ artist: "Edward Aldwell", spotifyID: "7joURQK6zh3yD7rRVOEEM2", popularity: 7.0 },
{ artist: "Sherry Finzer", spotifyID: "5udY4J3ruydRyg98yxTRHw", popularity: 32.0 },
{ artist: "Patrick Cowley", spotifyID: "1pggi3bfbAPkwrylE63MEO", popularity: 44.0 },
{ artist: "Al \"Jazzbo\" Collins", spotifyID: "4mO6efLv3fWlcX0se3wuMT", popularity: 2.0 },
{ artist: "Steve Alaimo", spotifyID: "3mnvGu4mOJr5MVVPtvaZo6", popularity: 8.0 },
{ artist: "Robert Bernhardt", spotifyID: "1BOu7Urnenjp0lxta0eu6X", popularity: 0.0 },
{ artist: "Chris Beard", spotifyID: "7hTEeJAMokCNuBxW8GtFKp", popularity: 22.0 },
{ artist: "Cab Calloway", spotifyID: "03cwCzIWQ8BRmXjGPDAL04", popularity: 45.0 },
{ artist: "JT Bowen", spotifyID: "0l4Yn0HdYU3SN4y3THrfcN", popularity: 0.0 },
{ artist: "Hank D'Amico", spotifyID: "0lyIpPcPMsttRNavePKtxd", popularity: 0.0 },
{ artist: "Blanche Calloway", spotifyID: "4Pb1I6ZTK7XnAfk7bJtvjh", popularity: 24.0 },
{ artist: "Claire Huangci", spotifyID: "6iFs9LvpM2UzZPmRtOrkLf", popularity: 27.0 },
{ artist: "Kill the Noise", spotifyID: "3qnMl4DHT4gndzFAcG4FlM", popularity: 61.0 },
{ artist: "Davey Havok", spotifyID: "1Q1ItjYrk6Si5q4tQtRbx8", popularity: 30.0 },
{ artist: "David Hochstein", spotifyID: "1faEXRotMvOft7MwY1xO3R", popularity: 0.0 },
{ artist: "Teddy Geiger", spotifyID: "1YIpZOfyHXMUgUaxxxgbaC", popularity: 42.0 },
{ artist: "Lou Gramm", spotifyID: "7CnmC3gRgLev4I609BrSxj", popularity: 43.0 },
{ artist: "Brann Dailor", spotifyID: "3uYZey63jgz1zJQ2Hu3urQ", popularity: 24.0 },
{ artist: "DJ Green Lantern", spotifyID: "2Fzxa58BAbUa6XVw8t2zkl", popularity: 39.0 },
{ artist: "Daniel Katzen", spotifyID: "32ijDAJ42vodlclM6b7bI1", popularity: 0.0 },
{ artist: "John Koerner", spotifyID: "7CA7FJBftyM0hSJaF6GWqT", popularity: 10.0 },
{ artist: "Lydia Lunch", spotifyID: "3aSkzI3DQrdPtYXizXnwda", popularity: 31.0 },
{ artist: "Jess Klein", spotifyID: "2KDZ8Vb3dZnQ8jnptHBdzD", popularity: 8.0 },
{ artist: "Sunny Jain", spotifyID: "0suWEroaXyqEB8JgDnccZU", popularity: 3.0 },
{ artist: "Dan Finnerty", spotifyID: "3ihlGBitf3qlPIgw1jYuDg", popularity: 0.0 },
{ artist: "David Diamond", spotifyID: "2PxsMrjxQdySklBP1NkO5g", popularity: 9.0 },
{ artist: "Steve Gadd", spotifyID: "42zoEf7IcpDSvdQjcrSpHl", popularity: 39.0 },
{ artist: "Lillie McCloud", spotifyID: "3nWu54EnxaBjMjfPhTdjRt", popularity: 12.0 },
{ artist: "John Mooney", spotifyID: "06qu5apaO4yt4gBL4G5F2J", popularity: 22.0 },
{ artist: "Don Mancuso", spotifyID: "2RWeacylOPilB2ejMEVAKZ", popularity: 0.0 },
{ artist: "Antonio Morelli", spotifyID: "3KtRC5v9fOgVq6ybEszv2P", popularity: 13.0 },
{ artist: "Roy McCurdy", spotifyID: "5jx7iddojZGfrIqTTDzkDO", popularity: 7.0 },
{ artist: "Ward Stare", spotifyID: "1w5rmqMmqiOpzAFxjiGBIA", popularity: 13.0 },
{ artist: "Bill Kelliher", spotifyID: "1D9b9H8HHaGR54KswAVIkp", popularity: 0.0 },
{ artist: "Allen Hulsey", spotifyID: "7qoeZ01NXcbAsa7xrA9AfU", popularity: 9.0 },
{ artist: "Gerry Niewood", spotifyID: "1JjvtLG0SFMrxJqziC2zZo", popularity: 10.0 },
{ artist: "Regina Sarfaty", spotifyID: "74j09FcN0u9Acal1tx4bqK", popularity: 11.0 },
{ artist: "Chuck Mangione", spotifyID: "2MMaIlHd8UvDW0mVRAncD6", popularity: 44.0 },
{ artist: "Emilio Rojas", spotifyID: "0ph1WGujzlmeYdaHfGf1co", popularity: 54.0 },
{ artist: "Joyce Sims", spotifyID: "4AL3YviSMI70ARkSOHlxbQ", popularity: 37.0 },
{ artist: "Ittai Shapira", spotifyID: "2I02qMlZRuFaA3KAiv6nUU", popularity: 9.0 },
{ artist: "Gap Mangione", spotifyID: "0mQU7aLi35kTXGf2WjKM35", popularity: 12.0 },
{ artist: "Tweet", spotifyID: "6zDBeei6hHRiZdAJ6zoTCo", popularity: 49.0 },
{ artist: "Joe Locke", spotifyID: "069uPv10UPCGukbtGRUkJk", popularity: 18.0 },
{ artist: "Giant Panda Guerilla Dub Squad", spotifyID: "0PHXRchyECGj96MB2v1xiP", popularity: 40.0 },
{ artist: "Wang Leehom", spotifyID: "2F5W6Rsxwzg0plQ0w8dSyt", popularity: 60.0 },
{ artist: "Mitch Miller", spotifyID: "0kLeQeOAEqHdFMUItesuij", popularity: 27.0 },
{ artist: "Stevie J", spotifyID: "61hrhoOBeupAeXFJeYhDGn", popularity: 23.0 },
{ artist: "Joe Romano", spotifyID: "6Tny4GyFk1w5CNO48Iz5pC", popularity: 8.0 },
{ artist: "Jeff Tyzik", spotifyID: "6B42Eg40dUN421zLzCrzlh", popularity: 21.0 },
{ artist: "Sarah Shook", spotifyID: "6ahZTaoJs2D0gcscsEx64r", popularity: 40.0 },
{ artist: "David Tronzo", spotifyID: "1cMdxLMEMONQUdLd8Kli6W", popularity: 2.0 },
{ artist: "Dan Welcher", spotifyID: "3xNifeP2FXSYhkOeH4gZnR", popularity: 5.0 },
{ artist: "Alec Wilder", spotifyID: "5L8m8ueO7e0vLH28R7yjcw", popularity: 14.0 },
{ artist: "Access to Arasaka", spotifyID: "5SFU7HLhBYOfksGMeRUKnR", popularity: 14.0 },
{ artist: "Rochester Orchestra", spotifyID: "5liQr6ap4vfqe1jISl3dan", popularity: 24.0 },
{ artist: "Joywave", spotifyID: "1UfzhwcOR4yfX7yHTPfC9m", popularity: 58.0 },
{ artist: "The Chesterfield Kings", spotifyID: "4azO6BF313cGEkFlGLtFWI", popularity: 15.0 },
{ artist: "Danny Thomas", spotifyID: "4w9baWHjc6mDIyAsGPQ5Cr", popularity: 15.0 },
{ artist: "Virus", spotifyID: "0NV5eY4Jzg4ldg2ikGnV4n", popularity: 48.0 },
{ artist: "Rustix", spotifyID: "5aAwq1ko4hT7TRc6cO7lKe", popularity: 2.0 },
{ artist: "SNMNMNM", spotifyID: "1IfnPPo89Yg1qx8wrAkpcs", popularity: 6.0 },
{ artist: "Alisa Weilerstein", spotifyID: "342cJoM4xzPrRfLb8fYkuh", popularity: 33.0 },
{ artist: "Rochester Philharmonic Orchestra", spotifyID: "5liQr6ap4vfqe1jISl3dan", popularity: 24.0 },
{ artist: "Matt Medved", spotifyID: "5xmKSoBLGN455TjWbaFcZa", popularity: 44.0 },
{ artist: "Soul Brothers Six", spotifyID: "1VPlW2qDDesSK0ZE0u7JXk", popularity: 23.0 },
{ artist: "James Rado", spotifyID: "34tBXZZ3Iyv0ge6rYTP1FX", popularity: 23.0 },
{ artist: "B.A.S.K.O.", spotifyID: "7n2JOxKGqWKxKkeBvh3pgW", popularity: 1.0 },
{ artist: "Eastman Wind Ensemble", spotifyID: "0uAndStTwdgOeHB1hnwBb3", popularity: 25.0 },
{ artist: "Ted Brown", spotifyID: "0073w3Aa69KsDFzaUlB7u1", popularity: 1.0 },
{ artist: "Carson Cooman", spotifyID: "3992yIQRjj0whoKIbtSaEp", popularity: 3.0 },
{ artist: "Charlie Lowell", spotifyID: "1pLPQDjgbUXbByCJ6A9sdS", popularity: 0.0 },
]

module.exports = rochesterNYArtists;
