[{ artist: "Susan Abod", spotifyID: "1lba5YhSLBZB1Sdv55m32W", popularity: 0.0 },
{ artist: "Roberto Mondragón", spotifyID: "7e986sT1AsXz5Gs1VX59n1", popularity: 2.0 },
{ artist: "Chroma Key", spotifyID: "6Bgd1CCQAWWqGbkmJsivLv", popularity: 28.0 },
{ artist: "John Crosby", spotifyID: "2Tq1nOZvidiakFdVCPYwaw", popularity: 0.0 },
{ artist: "Pictureplane", spotifyID: "5E1yjMbMNS3ghJbXtEvQCe", popularity: 32.0 },
{ artist: "Christine Albert", spotifyID: "7FOElbJMOpcElIXxoSiGRN", popularity: 3.0 },
{ artist: "Paul Ellison", spotifyID: "2iCOwJ2u5WXBrwFl9qwdb4", popularity: 0.0 },
{ artist: "Ottmar Liebert", spotifyID: "1AhYnfs5mzb3ennyLFXlYD", popularity: 47.0 },
{ artist: "Sean Marshall", spotifyID: "5jR6zZugUWoU9PClPLoFa2", popularity: 29.0 },
]