const stLouisMOArtists = [{ artist: "Al Caldwell", spotifyID: "2KiE9SatKB0q4k0k1510Dh", popularity: 0.0 },
{ artist: "Harry Babbitt", spotifyID: "1f63xLVV20bhJScsuKfJyb", popularity: 11.0 },
{ artist: "Joanna Brouk", spotifyID: "3yITaOTDcBPYNnYxlxQuUt", popularity: 29.0 },
{ artist: "Tommy Bankhead", spotifyID: "5TaE3MpQr2zk0OZ6mce22K", popularity: 0.0 },
{ artist: "Dakota Bradley", spotifyID: "6QoxzoWKLmiQmHChfmRsd1", popularity: 14.0 },
{ artist: "Erin Bode", spotifyID: "3J6OxkhyHNrmrAGPcv3x3i", popularity: 16.0 },
{ artist: "Tom Brooks", spotifyID: "42vVeB1O6kEejBCnu2vlqM", popularity: 11.0 },
{ artist: "Billy Bush", spotifyID: "1q4NkYMGXt3GIaohxAFSHy", popularity: 1.0 },
{ artist: "Julia Bullock", spotifyID: "4hpewChG7FAL2dYXLZUO44", popularity: 6.0 },
{ artist: "Metro Boomin", spotifyID: "0iEtIxbK0KxaSlF7G42ZOp", popularity: 81.0 },
{ artist: "Lester Bowie", spotifyID: "3r0t2sPG17gaUgXDJyJmHf", popularity: 12.0 },
{ artist: "Richard Egan", spotifyID: "2YKq9uiY4wpUTfP0MeRfNj", popularity: 0.0 },
{ artist: "Jules Blattner", spotifyID: "4Lznh7v8EwppuvfN8BPT1n", popularity: 0.0 },
{ artist: "Jason Danieley", spotifyID: "0WZeAgkdC5N2uTCrTBUttb", popularity: 26.0 },
{ artist: "Jim Byrnes", spotifyID: "2hOv5VWJDxxG4yR83LgU1F", popularity: 20.0 },
{ artist: "Barbara Carr", spotifyID: "2lYBbetPmx8ZwYGfpiTMMe", popularity: 15.0 },
{ artist: "Shorty Baker", spotifyID: "7DP7PBKuVbfPeShXxvQjXA", popularity: 3.0 },
{ artist: "Jennifer Johnson Cano", spotifyID: "2Jy2k3QXSRc15kxvvD2PtU", popularity: 11.0 },
{ artist: "Baikida Carroll", spotifyID: "0zDDoKS1groXaQXVBz6FHU", popularity: 4.0 },
{ artist: "Grace Bumbry", spotifyID: "6cn8cbQSuZWmAQSzBPBIsf", popularity: 24.0 },
{ artist: "Joseph Bowie", spotifyID: "1Zon9PRaebpEyaRSBY28UA", popularity: 7.0 },
{ artist: "Scott Andrews", spotifyID: "0EpJBCs611TxLeRspaNgfq", popularity: 0.0 },
{ artist: "Edgar Bateman", spotifyID: "5uLtT9SVWvkkEVJr7n1n5r", popularity: 0.0 },
{ artist: "Milt Buckner", spotifyID: "6R8OZtD9TL5Wki7Shzm8fb", popularity: 26.0 },
{ artist: "Ellen Foley", spotifyID: "0puypnsWTRY3cwySIyMjhe", popularity: 30.0 },
{ artist: "Sheryl Crow", spotifyID: "4TKTii6gnOnUXQHyuo9JaD", popularity: 68.0 },
{ artist: "Eugene Church", spotifyID: "3BDouLYmuh1r6CcUJaHPk0", popularity: 7.0 },
{ artist: "Damon Davis", spotifyID: "6F0z82ns1NVYucevIiWGZ1", popularity: 1.0 },
{ artist: "Sam Carr", spotifyID: "7lb4omwGsEoOE2yg5LJESx", popularity: 0.0 },
{ artist: "Fontella Bass", spotifyID: "6k3YMXJ1MJLgUEAlSPC6hA", popularity: 53.0 },
{ artist: "Kelvyn Bell", spotifyID: "2tfzHfg1ABRM1SqxSMc0X8", popularity: 0.0 },
{ artist: "Chuck Berry", spotifyID: "293zczrfYafIItmnmM3coR", popularity: 66.0 },
{ artist: "Amber Bullock", spotifyID: "2UM3duwCMBDd8EykmBNOjw", popularity: 26.0 },
{ artist: "David Eiland", spotifyID: "0EIqaUXA6uEWy0MTE2kQSI", popularity: 0.0 },
{ artist: "Louis Chauvin", spotifyID: "0J4WQJHLliFc4nnIAxIsyn", popularity: 2.0 },
{ artist: "John Edwards", spotifyID: "1Gf1FKIQV2KGbwHaWT7zGc", popularity: 24.0 },
{ artist: "Adia", spotifyID: "1HKGjRPwI0gaFyv4aSWPPl", popularity: 37.0 },
{ artist: "T Bone Burnett", spotifyID: "1H4NiejcEF0JfHRyLXtdME", popularity: 28.0 },
{ artist: "Hamiet Bluiett", spotifyID: "0CwLl45yTdzGtaA0izZ4Y0", popularity: 7.0 },
{ artist: "Jeremy Davenport", spotifyID: "1m92PWOv5wxo8bLH5CUOrn", popularity: 7.0 },
{ artist: "Thom Donovan", spotifyID: "5qA1t3T5DDt2KWUCCHO0hY", popularity: 0.0 },
{ artist: "Janice Gaines", spotifyID: "5Lhj3Zhqnh4r33iU0tnecc", popularity: 24.0 },
{ artist: "Larry Davis", spotifyID: "27feE7HAmTov8QoZAp1y3A", popularity: 32.0 },
{ artist: "Billy Davis Jr.", spotifyID: "090k1Fxa70NDQvkXmQBUfW", popularity: 33.0 },
{ artist: "Karl George", spotifyID: "4hnTe8PvgvzDVsSoDagn84", popularity: 0.0 },
{ artist: "Martha Bass", spotifyID: "38Yh0lcgmZkbhJMcrW8r0L", popularity: 2.0 },
{ artist: "Greg Danner", spotifyID: "2C0HlmnOgnne6R1acG3Khb", popularity: 1.0 },
{ artist: "Marty Ehrlich", spotifyID: "0xGR4aZBobtGGGCMBeGHbg", popularity: 7.0 },
{ artist: "Grant Green Jr.", spotifyID: "0O785OpmvnKip4KeS9ShnO", popularity: 4.0 },
{ artist: "Katherine Henderson", spotifyID: "76N6L4ZZZ98lbw78vea5Xb", popularity: 0.0 },
{ artist: "Chad Smith", spotifyID: "4DW34vji6G9GgGY0k2mic7", popularity: 27.0 },
{ artist: "Shirley Brown", spotifyID: "5EORJzqrFf7pwweCv9fUnV", popularity: 37.0 },
{ artist: "Richard Fortus", spotifyID: "7jqNmhdB9e4ghLLBXTQAbF", popularity: 1.0 },
{ artist: "Ken Ford", spotifyID: "0kgPQk9IMYDITCUUJkhsbZ", popularity: 13.0 },
{ artist: "Jay Fay", spotifyID: "016IAhAzE9pcX4UbMYg4Ao", popularity: 33.0 },
{ artist: "Malcolm Frager", spotifyID: "3BVjGj3O0aogPlKb1W07gw", popularity: 15.0 },
{ artist: "Jimmy Forrest", spotifyID: "2AdOGwpXiwCctV1n9sJaub", popularity: 36.0 },
{ artist: "JayFrance", spotifyID: "4OUcNlkvZJinR3eovDRmiG", popularity: 0.0 },
{ artist: "Steve Ewing", spotifyID: "33pNdUBSI7UfjdRHxlUwKB", popularity: 2.0 },
{ artist: "Bryan Greenberg", spotifyID: "2s7yDhxYxmB8aq5Skh3oTG", popularity: 22.0 },
{ artist: "Scott Hayden", spotifyID: "4gzXNZoFM5RnJC39A4QjmE", popularity: 24.0 },
{ artist: "Grant Green", spotifyID: "6dAtGAnHCQ1ujMUZ9Ep82k", popularity: 47.0 },
{ artist: "Ernie Isley", spotifyID: "3zgBwOoVIZBiNd3wIrKnhS", popularity: 33.0 },
{ artist: "Jai", spotifyID: "24V5UY0nChKpnb1TBPJhCw", popularity: 63.0 },
{ artist: "Kathryn Grayson", spotifyID: "6YFR1qpC0ZAFRvzVVNaBCU", popularity: 16.0 },
{ artist: "Edith North Johnson", spotifyID: "1SUHWGGIsGQq6WDWV03ETc", popularity: 0.0 },
{ artist: "Ella Jenkins", spotifyID: "2AdaJlzNcOpdrvMSBN92Wp", popularity: 34.0 },
{ artist: "John Hartford", spotifyID: "0NAr5zThPfMx26ISgooQK6", popularity: 43.0 },
{ artist: "Ronald Isley", spotifyID: "6W9RUw7xnNRYtgh8dimg7L", popularity: 51.0 },
{ artist: "Luther Ingram", spotifyID: "5Pek6HAr0BoHD9P1RuA7d5", popularity: 33.0 },
{ artist: "Geraldine Hunt", spotifyID: "2VuXufMFvhdWTYGEVceBdV", popularity: 29.0 },
{ artist: "John Harkins", spotifyID: "5WViWV5RAncZptHM2PYczf", popularity: 0.0 },
{ artist: "Greg Guidry", spotifyID: "7roC13N5Y9u1X6L95ngCqJ", popularity: 5.0 },
{ artist: "Bob Gordon", spotifyID: "4TMVw9T78FpJz81ZRLg1Os", popularity: 5.0 },
{ artist: "Jeremiah Johnson", spotifyID: "4pfYoLSuE39PBkHV4ntP2F", popularity: 17.0 },
{ artist: "Donny Hathaway", spotifyID: "0HU0U9kdXEHZVxUNbuQe8S", popularity: 62.0 },
{ artist: "Carl Fenton", spotifyID: "5gcxTbbCvzQcH2MCrLcYXN", popularity: 0.0 },
{ artist: "J.R.", spotifyID: "7sMcWECQxLm7EoKdRlSCAn", popularity: 45.0 },
{ artist: "Pokey LaFarge", spotifyID: "6hAUCkzZpoYGObd8qFW5TT", popularity: 42.0 },
{ artist: "Lamonte McLemore", spotifyID: "0ncF8LV1RQSdm1GJZYFiOq", popularity: 0.0 },
{ artist: "Johnnie Johnston", spotifyID: "2N8IGAlqW9mc9nxVlYcCuG", popularity: 0.0 },
{ artist: "Angel Olsen", spotifyID: "6mKqFxGMS5TGDZI3XkT5Rt", popularity: 61.0 },
{ artist: "Ryan McAdams", spotifyID: "0ajm0dBpwxK4ZNQlcCx3ud", popularity: 1.0 },
{ artist: "Gene Lake", spotifyID: "5vv5RyRxEz27enbZd5kwix", popularity: 2.0 },
{ artist: "Jimmy McCracklin", spotifyID: "58CohJpaPmE4H0fXEAnt4i", popularity: 20.0 },
{ artist: "Geeta Novotny", spotifyID: "4vhiF4RAnwcbhWpNhun2oA", popularity: 0.0 },
{ artist: "Tom Kennedy", spotifyID: "2CVXkyBi1KDvZeA23OHAW7", popularity: 20.0 },
{ artist: "Jay Oliver", spotifyID: "6JwgVuyqtvjIvTqHuNrK72", popularity: 28.0 },
{ artist: "Louise Post", spotifyID: "3u1RBHEOlOkV5E3mihCQ4z", popularity: 21.0 },
{ artist: "Mike Jost", spotifyID: "33ZDelxwo49wwvij3E68sq", popularity: 0.0 },
{ artist: "Oliver Nelson", spotifyID: "4QAp87iZerUP9PKxtLhmW1", popularity: 54.0 },
{ artist: "David Peaston", spotifyID: "5ZeRisPaRXTmDDzO8p11TA", popularity: 13.0 },
{ artist: "Greg Osby", spotifyID: "1O62I5mxJcYBXcIzY6IMYT", popularity: 25.0 },
{ artist: "George A. Norton", spotifyID: "7h6ij6Q4htSnJWmITuvZwO", popularity: 0.0 },
{ artist: "Cheneta Jones", spotifyID: "1Hz78kPUFMJuWTfva1OXS2", popularity: 5.0 },
{ artist: "Wendell Marshall", spotifyID: "7dtCBDAkstB46rshLCobHB", popularity: 16.0 },
{ artist: "Bob Kuban", spotifyID: "6mvCluPyR7DZS5PTHNjp5O", popularity: 9.0 },
{ artist: "Taylor Momsen", spotifyID: "31Wr64NZlSHgS0Gz6yoCr5", popularity: 14.0 },
{ artist: "Steve Kirby", spotifyID: "6uBg0MMgqWRIRVkMVSwEV6", popularity: 0.0 },
{ artist: "Robert McFerrin", spotifyID: "0weB412mGXxh2KfWwQHKlY", popularity: 4.0 },
{ artist: "Virginia Liston", spotifyID: "1Fl6swWf1Dh2YkRENDIbzS", popularity: 4.0 },
{ artist: "Kim Massie", spotifyID: "6Uj5KeZg7DJ4TvTLZXnqGU", popularity: 4.0 },
{ artist: "James Pankow", spotifyID: "4YLqD3oheyIvfEvX9Wckrt", popularity: 1.0 },
{ artist: "Michael McDonald", spotifyID: "24hJWbo98sH84tb0nkeaqy", popularity: 57.0 },
{ artist: "Billy Lawrence", spotifyID: "4d7h2InTvZxOd2JC3EBDLe", popularity: 22.0 },
{ artist: "Lightnin' Slim", spotifyID: "6MNoS1yW9FWwlYFaGjkz72", popularity: 18.0 },
{ artist: "Samuel Mayes", spotifyID: "6cadUgfpZnopFv8GuvPCLj", popularity: 0.0 },
{ artist: "Bobby McClure", spotifyID: "51XxxtoLP1n34IUdyuIn4Z", popularity: 18.0 },
{ artist: "George Rasely", spotifyID: "6mVArhjtKBFK0Qlivlj1N4", popularity: 0.0 },
{ artist: "Zella Jackson Price", spotifyID: "70hYUuUIyzFgmfCuM0hCfR", popularity: 2.0 },
{ artist: "D. H. Peligro", spotifyID: "6gwEFlhFNYf3RtgGL3mmWG", popularity: 0.0 },
{ artist: "Kevin Puts", spotifyID: "7pDJO8SaJGGhj8SxILieci", popularity: 15.0 },
{ artist: "Helen Phillips", spotifyID: "3gNVpFcW9xiS3aOhFB1ala", popularity: 3.0 },
{ artist: "Theo Peoples", spotifyID: "7JoUtoVdYF0HwREcQXhQ8b", popularity: 0.0 },
{ artist: "Scott Joplin", spotifyID: "5FgkTUuCNKDlilidPvZqOq", popularity: 44.0 },
{ artist: "Irene Scruggs", spotifyID: "62LgOe59ZekgJGyPDxRcH4", popularity: 2.0 },
{ artist: "Lucia Pamela", spotifyID: "64rgb5J7G8PnfhuvFST1d9", popularity: 5.0 },
{ artist: "Eric Person", spotifyID: "1eFOBzmN5JDatGukvMfclQ", popularity: 1.0 },
{ artist: "Jackie Ross", spotifyID: "1c9ivsDITvYJmYqbtF02FT", popularity: 23.0 },
{ artist: "Ann Peebles", spotifyID: "5dM7jA0PXh0Ozz8LT2YOCB", popularity: 52.0 },
{ artist: "Billy Peek", spotifyID: "0yXQSVEFI6ZPF9I5VXIHN1", popularity: 1.0 },
{ artist: "Mallori Nicole", spotifyID: "5aRUr2Fbfgf7LWJUXb4VP5", popularity: 0.0 },
{ artist: "Joe Kayser", spotifyID: "5I07bH2Oq5fHSRCNw1Bk8n", popularity: 0.0 },
{ artist: "Rick tha Rular", spotifyID: "7akRO7zCf0HZUji697nZtu", popularity: 0.0 },
{ artist: "Leo Sirota", spotifyID: "11Q8xLEqR5HbSaRUyjbcuH", popularity: 0.0 },
{ artist: "Bobby Sheen", spotifyID: "4nXmXA3DSTnMbVlZcjUCcv", popularity: 16.0 },
{ artist: "Korla Pandit", spotifyID: "5s2iRBZgWm3LHYiU8TGBJY", popularity: 10.0 },
{ artist: "Gene Phillips", spotifyID: "6zSbh85I98uX1rDXjLf0cJ", popularity: 0.0 },
{ artist: "Matt Schulze", spotifyID: "6AuwR83trWLyyUIm4wBmaQ", popularity: 0.0 },
{ artist: "C. Sharpe", spotifyID: "2sk41pP8cwtiRkGVsKBZb6", popularity: 0.0 },
{ artist: "Stephanie Trick", spotifyID: "6L20dqndLqtpmVZjEvgI3e", popularity: 10.0 },
{ artist: "Felix Slatkin", spotifyID: "0hMlAysclMQf5i0QKFUuPA", popularity: 16.0 },
{ artist: "John Long", spotifyID: "5x9DWz6SpEVu9NgL8aktm2", popularity: 29.0 },
{ artist: "Marion Telva", spotifyID: "0BCs3xtMVAAWb5jg7hQHg6", popularity: 0.0 },
{ artist: "Sylk Smoov", spotifyID: "6AgV8ZgFLzzAeIop4GUBGn", popularity: 4.0 },
{ artist: "Pee Wee Russell", spotifyID: "61EY7PIU7wT3t3766ZTvqB", popularity: 17.0 },
{ artist: "Mark Sparks", spotifyID: "5g9nN2dnO4r7JHGoKObNgb", popularity: 5.0 },
{ artist: "Oliver Sain", spotifyID: "4edwXsmUVRa8EneehcvoFE", popularity: 21.0 },
{ artist: "David Robertson", spotifyID: "2Wyq1VPgjZgRPQTUmqoFcj", popularity: 33.0 },
{ artist: "Ben Shive", spotifyID: "2HOxXL6fxCe1OAEPw7sgTB", popularity: 9.0 },
{ artist: "Eva Taylor", spotifyID: "4tcdCfYOTLmHkjzfIIHocL", popularity: 12.0 },
{ artist: "Kay Thompson", spotifyID: "2iHiqwlS40GTFt8eELeoHr", popularity: 23.0 },
{ artist: "DJ Tab", spotifyID: "3alSl4w3PYmu3Jzb5Bg6ey", popularity: 12.0 },
{ artist: "Bennie Smith", spotifyID: "023yHzWdxknrNbytFc3RmF", popularity: 0.0 },
{ artist: "Helen Traubel", spotifyID: "4Nxww4dXloz8YCEhCfLJqs", popularity: 4.0 },
{ artist: "Walter Scott", spotifyID: "5rVqKL7Bz3AQmvqBWL2AiG", popularity: 21.0 },
{ artist: "Henry Townsend", spotifyID: "3e32BiHqQapOCijTcTmEHs", popularity: 5.0 },
{ artist: "Cal Tjader", spotifyID: "3XOVABzceOUTbR3iEz0ImO", popularity: 44.0 },
{ artist: "Toya", spotifyID: "6cStgiv1qH5z6GYrFsjuGj", popularity: 52.0 },
{ artist: "Ronald Stein", spotifyID: "0BiPWTuRSneWIrAnue7BVZ", popularity: 4.0 },
{ artist: "Clark Terry", spotifyID: "62xdwGEOLoGQxKUqoJusyU", popularity: 36.0 },
{ artist: "Floyd Smith", spotifyID: "1JJIMOAOekW2O6wex5tLUY", popularity: 0.0 },
{ artist: "Willie \"Pdub\" Moore Jr.", spotifyID: "5kA0oFclMEHhKDQO8pQX5T", popularity: 9.0 },
{ artist: "Ward Stare", spotifyID: "1w5rmqMmqiOpzAFxjiGBIA", popularity: 14.0 },
{ artist: "Charles Whittenberg", spotifyID: "2WcGCbYdsXDHpF4rWI64h6", popularity: 0.0 },
{ artist: "Jim Wearne", spotifyID: "0SDQTedCTwcw7TTDaMJIg6", popularity: 0.0 },
{ artist: "Orrin Tucker", spotifyID: "4JEQHL9mfMdmT1tKXXq4vV", popularity: 10.0 },
{ artist: "Phillip Wilson", spotifyID: "6zpgFIMlJePts4EYaGq3X5", popularity: 4.0 },
{ artist: "Chingy", spotifyID: "3s2wTjWxK8NOX09dmsvVOh", popularity: 61.0 },
{ artist: "Harold Wheeler", spotifyID: "1JGhBHVnIjGGnDUSurfCos", popularity: 0.0 },
{ artist: "Dan Wool", spotifyID: "6iwVkcqRy3WZ81ARvbTGMD", popularity: 0.0 },
{ artist: "Oscar Washington", spotifyID: "5TvZooYTLCBxJdj6XZuYo0", popularity: 1.0 },
{ artist: "Akon", spotifyID: "0z4gvV4rjIZ9wHck67ucSV", popularity: 79.0 },
{ artist: "Olly Wilson", spotifyID: "6fVTaBjQAo2EkUHjHT6eMJ", popularity: 0.0 },
{ artist: "Ben Weber", spotifyID: "0FK1zXQhV2DnGPmOOhIrNu", popularity: 0.0 },
{ artist: "Felicia Weathers", spotifyID: "6sd4iTO3BVWDV4jh6ATSpx", popularity: 11.0 },
{ artist: "Evelyn Turrentine-Agee", spotifyID: "4JxFWHeZALDa5vZGT7PW6m", popularity: 19.0 },
{ artist: "Kristeen Young", spotifyID: "6g01WfakTZUoArOiHWwVos", popularity: 16.0 },
{ artist: "City Spud", spotifyID: "3L2SIGZah4QZSvN4wC8rHl", popularity: 60.0 },
{ artist: "John Webber", spotifyID: "03xXcbbFNqZUU3ENJcY8a0", popularity: 15.0 },
{ artist: "Carl Weingarten", spotifyID: "5cY2PYBBka3bsgMxytGmzN", popularity: 3.0 },
{ artist: "Thi'sl", spotifyID: "1Q45nhioxaxZTDjR0iaMWp", popularity: 42.0 },
{ artist: "Jimmy Woods", spotifyID: "6ZIvxJcBaPTqcDuzWGuqyJ", popularity: 17.0 },
{ artist: "Dave Weckl", spotifyID: "6h0KtnUiBpkxxjvZZPvNSw", popularity: 38.0 },
{ artist: "Comethazine", spotifyID: "1iJdyDcY98X3GMnUesl7tf", popularity: 75.0 },
{ artist: "Jackie Hill-Perry", spotifyID: "0Lf9qKpKwy6fJtfM7UWLV0", popularity: 36.0 },
{ artist: "Stevie Stone", spotifyID: "2IvPBSC4CgNLYC1GHEAxcN", popularity: 51.0 },
{ artist: "Shorty da Prince", spotifyID: "1gd7H2UkSUK51FjALSbShi", popularity: 6.0 },
{ artist: "Jibbs", spotifyID: "4USNIVeRwXIAdbVSTqelbh", popularity: 45.0 },
{ artist: "Yung Ro", spotifyID: "1mQWZPciU2mObkw2Fpgbxg", popularity: 20.0 },
{ artist: "Murphy Lee", spotifyID: "78OAtwN3XpjMcjibnF2Kw5", popularity: 60.0 },
{ artist: "J-Kwon", spotifyID: "1Zz5UxfKSSqc6hpa3xJPCw", popularity: 56.0 },
{ artist: "Smino", spotifyID: "1ybINI1qPiFbwDXamRtwxD", popularity: 71.0 },
{ artist: "Huey", spotifyID: "7A9yZMTrFZcgEWAX2kBfK6", popularity: 65.0 },
{ artist: "Kyjuan", spotifyID: "6kD993mKIytiN9sE6VyRfa", popularity: 47.0 },
{ artist: "Bullets and Octane", spotifyID: "6Ku6HNSfgFrk2c3KIlf2j9", popularity: 38.0 },
{ artist: "Json", spotifyID: "5eAZLsVlw4VKkwtQS9cfrX", popularity: 33.0 },
{ artist: "Blinded Black", spotifyID: "3zKM4BZHXSAC9W0IaJPGtm", popularity: 3.0 },
{ artist: "Cavo", spotifyID: "7a06JYLmZG3txQqr9uzvbg", popularity: 40.0 },
{ artist: "Tiffany Foxx", spotifyID: "1ssxQyjMTgIt7xBlsK3Y7O", popularity: 22.0 },
{ artist: "William Zeitler", spotifyID: "5KMzfLKmcTza3BJQ5CFdye", popularity: 3.0 },
{ artist: "Mosaic Whispers", spotifyID: "0fP33MCfVUaPivyFYLZtoh", popularity: 9.0 },
{ artist: "Flame", spotifyID: "6f4XkbvYlXMH0QgVRzW0sM", popularity: 69.0 },
{ artist: "Angela Winbush", spotifyID: "1EIgKOrzyOQRB3l43EfymN", popularity: 41.0 },
{ artist: "Calico System", spotifyID: "7bkm41OaTg2flicTu0ddKE", popularity: 5.0 },
{ artist: "Gentleman Auction House", spotifyID: "5e7sOgwcgPcAyTZJhx0ic6", popularity: 1.0 },
{ artist: "Dazzling Killmen", spotifyID: "6LRoi2IPw3QzicBWx0ZSgj", popularity: 8.0 },
{ artist: "Anacrusis", spotifyID: "42RvW31Dl6ScQWWLC0G6XP", popularity: 15.0 },
{ artist: "Laclede Quartet", spotifyID: "4zJl38IRFSC8Cjio1UqFn3", popularity: 4.0 },
{ artist: "Gravity Kills", spotifyID: "3V3ChkwvlWDJtMFuOKfYiB", popularity: 34.0 },
{ artist: "Building Rome", spotifyID: "3T112OVy9EfbU3wdWTLJSu", popularity: 2.0 },
{ artist: "Foxing", spotifyID: "2dfxY7YDuYCUtWFzWTS6IR", popularity: 49.0 },
{ artist: "The Five Du-Tones", spotifyID: "1qDxvNPoEt0quatnm19u9i", popularity: 9.0 },
{ artist: "In the Midst of Lions", spotifyID: "7JXvvITCFPtUixT0kxsgCu", popularity: 22.0 },
{ artist: "Bunnygrunt", spotifyID: "5b9BMCXzkqOps3uV8m9XNu", popularity: 6.0 },
{ artist: "American Wrestlers", spotifyID: "4Gb5VLPjii00h1GmhGRzX7", popularity: 14.0 },
{ artist: "Black Fast", spotifyID: "7hxDsJyld0SlN7N6FXYG20", popularity: 18.0 },
{ artist: "Blind Idiot God", spotifyID: "62me5s0cOQW390yg6cocWG", popularity: 7.0 },
{ artist: "Greek Fire", spotifyID: "3sqggE8rqIXZjB68hPbhen", popularity: 39.0 },
{ artist: "Honeytribe", spotifyID: "2DeZvxuuujXhd3Xhk3jd3g", popularity: 9.0 },
{ artist: "Living Things", spotifyID: "0DENRoU3voKkcF01nyoaqX", popularity: 25.0 },
{ artist: "Last Nights Vice", spotifyID: "25VQCkxFRGTsIVvWChmQxL", popularity: 0.0 },
{ artist: "MU330", spotifyID: "1kCnkCPBvBQFZv6njWcD7x", popularity: 26.0 },
{ artist: "Rockwell Knuckles", spotifyID: "1H4y0qrdrs5gHSSJH2droY", popularity: 4.0 },
{ artist: "Kings of Rhythm", spotifyID: "47V7QCymL7BMSADw2RrKdD", popularity: 29.0 },
{ artist: "So Many Dynamos", spotifyID: "0aLg9VUnQAulb6n3l1L0Fe", popularity: 13.0 },
{ artist: "Pavlov's Dog", spotifyID: "3ZTpSMKKljfomqVgeJGwDL", popularity: 32.0 },
{ artist: "Disturbing the Peace", spotifyID: "411czbEFlrZuqNIAOOEarR", popularity: 1.0 },
{ artist: "Gob Iron", spotifyID: "4urNBE8q5xkh85r88PgHgh", popularity: 5.0 },
{ artist: "Kentucky Knife Fight", spotifyID: "034POI89c89YcMCarhv6AO", popularity: 2.0 },
{ artist: "The Rats & People Motion Picture Orchestra", spotifyID: "5VyWJdIxzddt7schPzok1P", popularity: 0.0 },
{ artist: "Human Arts Ensemble", spotifyID: "06PlE6QTJ2ShxheP9uKnxq", popularity: 0.0 },
{ artist: "One Lone Car", spotifyID: "4lmnF6hpUMcKwJkkI8pD2Y", popularity: 0.0 },
{ artist: "Mama's Pride", spotifyID: "2I4OgzVQU7t8Te64B9rtSU", popularity: 13.0 },
{ artist: "7 Shot Screamers", spotifyID: "36aQeRKmpA8RNsWIsOF0uu", popularity: 14.0 },
{ artist: "Revolution One", spotifyID: "167daJnN2d1urB6l8bRFBr", popularity: 24.0 },
{ artist: "Solar Trance", spotifyID: "3pP6eQzl780kQ8SDUvcOMV", popularity: 0.0 },
{ artist: "St. Louis Symphony Orchestra", spotifyID: "6JOWtalPQ8ldlaZ7w8eON1", popularity: 0.0 },
{ artist: "Modern Day Zero", spotifyID: "5WzngE3glloMeAAUkn2vVn", popularity: 13.0 },
{ artist: "Ou Où", spotifyID: "22JbAaWA5Abf5esf6N4PHY", popularity: 34.0 },
{ artist: "Ludo", spotifyID: "6ok7bEDf9CZ0448D59AaNL", popularity: 44.0 },
{ artist: "Son Volt", spotifyID: "7AhDVqsNA5q46WKsRPXvoe", popularity: 46.0 },
{ artist: "Adair", spotifyID: "5gYIhpLwCYoxh3V8KANZpI", popularity: 57.0 },
{ artist: "Radio Iodine", spotifyID: "3jJR1d2PcqvHLZrhQN7hbo", popularity: 3.0 },
{ artist: "Ol' Skool", spotifyID: "2Sic3e2rD0kCiltCyCczZR", popularity: 21.0 },
{ artist: "So They Say", spotifyID: "2JKNM98rMRZwzf5EIjDH2i", popularity: 19.0 },
{ artist: "Prince Ea", spotifyID: "7v57fCWxYGDdhK7dG7RPTc", popularity: 26.0 },
{ artist: "Scene of Irony", spotifyID: "7C8kMXlBa3sxJOgKvkUtm3", popularity: 0.0 },
{ artist: "Saint Louis Chamber Chorus", spotifyID: "5ZbPQt4QaKbifoHJgn5Mb6", popularity: 0.0 },
{ artist: "Ali", spotifyID: "4rTv3Ejc7hKMtmoBOK1B4T", popularity: 79.0 },
{ artist: "Nelly", spotifyID: "2gBjLmx6zQnFGQJCAQpRgw", popularity: 76.0 },
{ artist: "The Ikettes", spotifyID: "4vNCmeT4klWtM1xgF0oohu", popularity: 26.0 },
{ artist: "Story of the Year", spotifyID: "0KDuKk6YdEu3hR56HtXmxt", popularity: 58.0 },
{ artist: "Uncle Tupelo", spotifyID: "2Plkkomsc4DKawkCioLKjc", popularity: 46.0 },
{ artist: "Well Hungarians", spotifyID: "30lCjq5SMlSvSVMePOollD", popularity: 0.0 },
{ artist: "Ike & Tina Turner", spotifyID: "1ZikppG9dPedbIgMfnfx8k", popularity: 57.0 },
{ artist: "Ultraman", spotifyID: "6cIISOIrMlAETGvI2FCqFR", popularity: 3.0 },
{ artist: "The Urge", spotifyID: "3ewpPJWBH1eiTYj9cZEce2", popularity: 33.0 },
{ artist: "Stir", spotifyID: "4RqnVnpq5R0R5rJKeV9pWc", popularity: 15.0 },
{ artist: "Sullen", spotifyID: "13CMfEeq8AC6ryGOPODqE1", popularity: 42.0 }
]

module.exports = stLouisMOArtists;