const trentonNJArtists = [{ artist: "Sarah Dash", spotifyID: "40GzTuEPg9xjzGeXJESEMH", popularity: 11.0 },
{ artist: "John Coates Jr.", spotifyID: "6LJviGGAtbD5f1DtyYbqbB", popularity: 3.0 },
{ artist: "Tim Kelly", spotifyID: "6jXOSlHv2XCMSTATjyaF9b", popularity: 0.0 },
{ artist: "George Antheil", spotifyID: "00iJnnUu476m1HX16e3por", popularity: 17.0 },
{ artist: "Johnny Coles", spotifyID: "0RKsF1pa3v0hhEeJbt5AxV", popularity: 23.0 },
{ artist: "Jake Weary", spotifyID: "6MzeyqrCC4X05IwpX9mVDp", popularity: 18.0 },
{ artist: "Hodgy", spotifyID: "4sXi6Uq6IzBaLfFi8wlb3I", popularity: 50.0 },
{ artist: "Scott Metzger", spotifyID: "0ZILxKPM8Y2vYZ1UToHidc", popularity: 9.0 },
{ artist: "Jerzee Monét", spotifyID: "3KNBFfutCpSyTAuIgX2eZV", popularity: 5.0 },
{ artist: "Brenda Hutchinson", spotifyID: "2dCp5RywShxoi5dWMZDH27", popularity: 0.0 },
{ artist: "Bob Sheppard", spotifyID: "0ilsxNHgUGAFmA5TfOOUf4", popularity: 12.0 },
{ artist: "Carman", spotifyID: "3kTcyaSYP5fqlqrNUvxiER", popularity: 35.0 },
{ artist: "Simone Hines", spotifyID: "4PP7LrQhtXgWKQ1STMwzya", popularity: 5.0 },
{ artist: "Steve Gilmore", spotifyID: "3LM1mEuYJvsCTFm3el50oa", popularity: 6.0 },
{ artist: "Richie Cole", spotifyID: "6j60GJXKhcNX1XqzuP8TXe", popularity: 20.0 },
{ artist: "Richard Hazard", spotifyID: "0L1WCce5ieDNn2qnNWOMfb", popularity: 0.0 },
{ artist: "Jonathan Dunford", spotifyID: "3UXqh07v5aOr5BbwBT1pYv", popularity: 10.0 },
{ artist: "Gloria Lane", spotifyID: "5cUZYavFJK2993FWYddh3w", popularity: 1.0 },
{ artist: "Philippe Djokic", spotifyID: "4AoVNtzLsH17wpx0MzPb60", popularity: 0.0 },
{ artist: "Orrin Evans", spotifyID: "1E4jlqY2HEXKLT0YkNy3HL", popularity: 18.0 },
{ artist: "Richard Crooks", spotifyID: "26Kcz3P3ONnOoPgZEu5i5j", popularity: 19.0 },
{ artist: "Willie Robinson", spotifyID: "1Jt5Hel6ypNFissptTSPfR", popularity: 0.0 },
{ artist: "Nona Hendryx", spotifyID: "5pTDagkiVMJC5DJtSAdbXg", popularity: 28.0 },
{ artist: "Drew Gress", spotifyID: "4HMyzDtVu6uNLYQZqYeOXK", popularity: 24.0 },
{ artist: "Michael Ray", spotifyID: "6ghiFYcwn2Vzl6K50U0UPz", popularity: 60.0 },
]

module.exports = trentonNJArtists;