[{artist:"Sean Rowe",spotifyID:"0h8q5Df7MVYUDg4Ic8IHwF",popularity:42.0},
{artist:"Super 400",spotifyID:"23ptZFAvGouf1LUXsXf3Qx",popularity:2.0},
{artist:"Tim Hauser",spotifyID:"6IJUHIjXKlWrpvRw6Xgois",popularity:0.0},
{artist:"Dick Halligan",spotifyID:"2XgdaUWvDI0hCYUpeMJizK",popularity:0.0},
{artist:"Nick Brignola",spotifyID:"3NrgXw9WrmjbnrAAM8aTHn",popularity:8.0},
{artist:"Laramie Dean",spotifyID:"2D5RVaGduosNUdgHulNAyN",popularity:0.0},
{artist:"Yvar Mikhashoff",spotifyID:"5LwhupssP5ofvgkk8PEX9I",popularity:3.0},
{artist:"Michael Bisio",spotifyID:"4i4kKMGfo993XYwl0Wt7n8",popularity:3.0},
{artist:"Robert Allen",spotifyID:"7xD9x4lsRnSjtfpUztjmFF",popularity:16.0},
{artist:"Patrick Conway",spotifyID:"0fQwdzFoArNB8DbFnCYRRO",popularity:0.0},
]